---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.1.3@sha256:d281d17d8ce92877f998cf1fc50131ce233bc4925d912d8a0213c8d582549fce
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
        hosts:
          - host: "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bazarr-tls
            hosts:
              - "bazarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        size: 3Gi
      media:
        enabled: true
        type: nfs
        server: "192.168.0.12"
        path: /mnt/hdd/k3s/nfs/media
        mountPath: /downloads
        readonly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2s
