apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:S+Yh3IbKAGPnAb8RAdef4AUuI7wWyA==,iv:lHevXWfXBjrCW1WYcyaurs/ykl6ycLdWacCSBr7122M=,tag:GbmuJyJyafSwkCrncYgiRQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Ks5EjKkM40D6zEvy2uKmkUXXLgtLsWPmjkhhekg0mg1inkL/qg==,iv:L+9ZMWalkr0K1YY3mPjUUnogRgqAwARw+IbWwjhrpvg=,tag:CW0XCneqgH80c+ECUWx3Jg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:RExmfB6t3pRVLap9DY7svXqc7cE=,iv:B6aeN7xE1uq4b1asKC+Dw5b5jIUx0t8BdkGl23zv0P0=,tag:o0SLKWD8VCoUNixIxVEPAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UzNEQzN2WDdlaUZzRzlp
            d1N0cithWUhoQ2pySERndzZYV2kyV0szZzBBCmcyQWljZGtLejZjUFJlTzdUS1lq
            YlMyNzJGbW4vOEhmaGttRVdlOVAzMUEKLS0tIHFBclVQdUhpa1k4NFBGWktUdWQv
            c1N5TEtqYUN6S3ZxTTEwSTJEb3EyTGsKG04guGCAFkg8jPvITgKAQeJz9lrfz5Ha
            mDi5urF3bThpMC2pyN17eQNGvbdVxBl7UetNsBaeHOt4euTuA5UM4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:55:33Z"
    mac: ENC[AES256_GCM,data:vOGxef1eMZzxDwPRHq+5O97aY/qYtO3yCFzYe64S1KhuuPT1AClGp1gS1flXMNdGHVFdzNmevxiwYx7C8dkrCiTOWVjrfTrfBgWJKvG8jeEBpNDKoUzyu85mJLZ3LQcWegCN/UIQm5r1UjyDZZIY1pssOLX2fQqZuZaeoENcy18=,iv:s1E0LNRR6qe88/iBkAQnmCILhG6sRLDCfOk/kuPs9h8=,tag:myKkZGcD/ZaSGKqL8qs/5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
