apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uXrmmzIULJpzh+Emj90hMu3UXLaq7w==,iv:FJQoiXQ7FZUxANiAluxkyTuO39dopDcaEAR6yzOLMSM=,tag:ex2D2UmcoBr/IzVEZJ5thA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:z/EzYT0dXV9o8uWtWefHmvByUHf7YZ2s0WmfJ8aLKgOcZ6v81w==,iv:IJuiphebkbCyNPAOED8iBVC7Af9S8UmJmhApP4N0AnI=,tag:RuuhMvoC6fp3GHxsmCJfbQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:90qlSAgYuoFRae6Rvc81Lev4E0o=,iv:S4/eh2ZHsHG4qXh+UnZjw6xrsPHpPlN5akg5cDnARW4=,tag:liRhwvOUyr5Cd2gr0U56KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U3ZyQ05NMVVUQnVOb3Zx
            K052aUZnUy9UZGlGVUgwZVF6WDVaSmNEOGcwClRITFR4eEFnaGJmU05Jc1FBa2lv
            RVdTWVAzc0JhRXNxRVFZYUo2blMwK1kKLS0tIDBRY3hmL2NsWmZaNmJlNmY4WWVp
            U25YaVIxVGlSUDRlTWhYTGJWTFhBdjAKH9aAKMj9j41IkfshCxCNuI3AD/cKbvKK
            I5lvSDjURlZ6TQ/BhlbURsny/fRFRBPtF/bz+CeWNR8bVx93gxalsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-09T14:10:52Z"
    mac: ENC[AES256_GCM,data:Rsg+lj5Wq/dGU7MJpU3LLxYK6Evl4NgJsYtTw73CGPaL7fkjmyFxHXjIkA2vQJ1ezR9D+Y+y8TPd1WPNw4qItbUN9PLlGBOAmG/HPeZYM8Jv9cYE8jFWsvAfI89ZaRLotXIA/PijqOECO1G/mlRJuZfAmyL0RmiN5X5rzYnWzWk=,iv:z/VxehS0NEGizJBRSoE3D4g4HooSeTADjpq7y4o657w=,tag:aZvi1zsb/87VXXNISxr/Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
