apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5Keo5fVXOTJHE6x/r1AbQYWKZvoDTw==,iv:mnoG0GTOdnteuNYqQvXM9eBRPcHiL3ZP0Wv6Fmzq46g=,tag:NwufN5Ci8ldF+i02VqMcIg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:WNfr5P4senETnWpCc6JxjLzictfMUJ8JW7qbIbjL6HFPFSyHng==,iv:0ZHpzEWBY8Buz3m5q9GIPJEyzqlqPO1OnWhu7JwLMhM=,tag:D/AC281rCckuN1nErhcb1A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:GauJ1gPe9Vomdn72LvRRCmzagzA=,iv:DQF/db2aRNef5FqxBs/HRjO2BTHiG7krfjUMWTvokmY=,tag:w5Pf8SBjZAgZahfH69qA8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ2QwMjVoZ1VIWUh5d1c1
            YzRUWjAxVFJrdlY3YmV4dWJlc1k3N2xRMGxFCkxvQUMvengrZ3JJbDFtdzJ6U3pL
            UG5LRmRmUExDY2NmOExnNDcrbUZ3T3cKLS0tIGR1L1VUc0hQQ1QrWktLMlp0YUZJ
            aEsyQUlneTVnOFZSSEpJbGNLVUovQmMKmHTUfIKA+v4pVrjNbbw6HST4TMjAuqa7
            6GcLt0NXiDZmehBLU6JlVf3IwiERLbIxzT+teGm3zFR2jPEg53gOww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T20:53:04Z"
    mac: ENC[AES256_GCM,data:BeC92yz+PPz8aiJ39p08ZKmkOoZRruHyB+q1+2xPCjmDHbRVG/KEAhgZZXmI8+VUOYjV930hgyme9UwrLXcr/9rSItgPt5bQh6/G5Ovrjb+wNpAjw86I5RZralcxCPkaxa3ynGIuNHJE6pxBeX59/gxdrOdLi1F/fZ+UjIb6Sr4=,iv:kn1bQ5Gt4N4PcqH5swxEjbUXqc4BqAL9wQGLI+s2o3w=,tag:+gmm5k2mUrf38kh7KYeOdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
