---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: downloads-gateway
      namespace: vpn
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.0@sha256:c070aa47a28188cf562c3a32a2855db5817145d7da7026a6acf0fc6d0c779481
    env:
      TZ: "Europe/Stockholm"
      QBITTORRENT__PORT: &port 80
      QBITTORRENT__BT__PORT: &port-bt 58182

    hostname: qbittorrent

    podAnnotations:
      setGateway: "true"

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs: ["${SVC_QBITTORRENT_ADDR}"]
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          # external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - "qbittorrent.${SECRET_DOMAIN}"

    podSecurityContext:
      supplementalGroups:
        - 100
