---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: palworld
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/thijsvanloef/palworld-server-docker
              tag: v0.17.0
            env:
              TZ: "${TIMEZONE}"
              PLAYERS: 16
              COMMUNITY: false
              MULTITHREADING: true
            envFrom:
              - secretRef:
                  name: palworld-secret
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.1.222
        ports:
          http:
            port: 8211
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host palworld.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        storageClass: openebs-hostpath
        type: persistentVolumeClaim
        name: palworld
        size: 25Gi
        globalMounts:
          - path: /palworld
