apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:sRX3iKs6p4SJavsEt9LY1DkSLaOxjjlgr04tHIR4f+oDs5qmX+Gijq8VEtnyFe7/WH6tPbPB78AJLattQTOSsglKmgUu2jbbiKwFAcfPhSo29xsWwNYaMfpTJLenjarDpVWgzpc+9dvUgagBCFvs6LeqK1B+CamGWNVEJsboHXQ7yD4aTUGzrqzbWyxPYWYRSejoWAMQGgzfLB7b1is3bHUs8O7LVaVhgNq8TtkMtkFdnItW4gp+23J9rxc2DMGyK72jNlTqRJ70jxg9tejoUqQPvkojynDcuk1fU+82haD+8AHFYOPenS7JzVD07m5+I/I8lkg9Xf3/fG1I8WlYwvFJWVEbHc880zWfx+5zOzMtLCToukEcKVxS5d26xhtv,iv:YzUVeQqc7Sej+EoreJ/zvH2EvHZl8ij1owTM7DAl1l8=,tag:Qe28ssdCfmLFcr0F0IlbWQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bGxCbGp1SmNNd3JkYTUr
            YlAzcEQ0V29ROG9WR0M3c0NDUTJNcms3YmdzCjBOYjJLRUE2RjE4MzgwKzk2RWp4
            K253MEtTekpDTWVqYW9TZDNURk1lQU0KLS0tIE55eis0OWN0bW1KWkc0b0pIVi9K
            TnBaRVRVYmphcWNEdThpRGx3RHVVSzQKb6K4m8TBO8zEBH0F3qd+3avez7GGPXbu
            kdagYrlIIXXtwKpgiiDHEPQSd/3+KZkWHrmlx/7sXLUBQIE2kDoTuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T20:24:45Z"
    mac: ENC[AES256_GCM,data:rrvzEx7Yc4n56MA3tSAasP+tHsvNfCVGKJR/g6NjxJWj4d879Q+4/NkK33A2sUGxcG94QGeGTz3CHg5WZbcV/2c/a5uB0NzTuI+1DDebDHmOeVmbxYDllQzuQ0/suVktZJTg9DGaHZ7QyFwp2LA3+5fqvsoDKWsWCCBfVqzrYHw=,iv:+3CVV5Pk4YcjquEcwKwE73pSjZFtLngng2InKrCOuUI=,tag:g50Rriur1L1nhQzrQaA+Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
