apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:oSsdtTxUDPegi5tiB++rI7O9LqM7boUpGwTlycX1CF6ZRUL/E5k2V0Jt2p4U1Y9q5740HO2BMpUcCjA+Ifrm/25siCkBcZlnQh+/veFeHGor7TIK4KOovvOg0py+fW+a0gBWCNKeP3ghprxruPxbqgL00qDIRZQSnTMl0Dc+Rj6Zdmb6H3vnjG8XQ0sOFDnwVvcFSSPSciybGbk7X6IOGJfa7G8MS1Ip,iv:+o3unLeR4iCUBo9Zn0/NT9bnDnKFhYpk4MiV+g5NNNg=,tag:KHTMrvHeo1H/L8vykbOA9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZDA1TEQ2VG1SNHdrZlRo
            TEN0clpVMmJiaUFqcWdTRUlDRnpRaXIwSlhBCnZoYTZwOUVUcXdWVEFCVURuUmZH
            c3NEK0tNbnpCTG45TWNSTWJGeUlXWkkKLS0tIGtLZllxalJZSHQyalZtdWRmTjhz
            ZWdnMUxJbUVJSC9DQ1dobThVVUhTUmMK2zIgfIoTcuAAEbeQ7GULnmBn5xC0ApBo
            QhblHyaokUBOrjQNRityATAcfAMeBvkUT2tKLJLYOttZX0aQiuVBFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T14:14:31Z"
    mac: ENC[AES256_GCM,data:AelaEtZDyI/ahoyI/pXd3AA2mN/QsrlHsMeTAjm6xb5aoqJ0uca+GzjI9TyI7Qgiqz9Eu1s6GILIM6tf1DSx5HDvYhxCSB2/eUMTWnZq+f9iBPTXozdlI4wxoeQC9n6E90LLtMsLnSx/3p8nC6UkgKe9NtLRYsF5t1/udnlsv+8=,iv:avCMhp+FbKOl8P0+UN6KuQTzJPcAIzsi4IGuC76Xnv8=,tag:IAPBV8hYsxqeGb4f6MVyQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
