# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YqUZlbFEfkQKsnPPVqZ02xc3JFIQzQ==,iv:2wFhOYw/P/7l7sRocvHIKGT7Yq2Qoa/beIqhnxXUt4g=,tag:sfDQ1j/Mjs0/ufzvwThBCw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:qEBlbP2exq+NfXfxyYafJkyrYzAkilu1eIZNtWh6yg5w6/Pg9w==,iv:nO6AkJDH9fSDtgz/LiCYlGDUA3GeyJs+DKvz72MppEs=,tag:umTt+xJ7hL+Jk+Ot6f3niw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Ob4FpCrPrQbGooreiJwJefnugE4=,iv:lzaDTm9x+fOlZlAp92UZh7m2picSoF/usnJew01XWSc=,tag:P7donzAEskjAcou1y3820Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QlRmYnJ3NTQrVDBVTVhm
            cSs1VGZ2S0h0Y3JsL0hTa2VJKzg4SW1PRWhnCjhPQTJEcitaQy8yYkMyaWc4TS9x
            RVRLd09hTWllY1M5ZHNKM1VrN0YwTEEKLS0tIG81bms0anBJQ0JPYitQejlGYkhq
            YVpPQXduS1gvZk5ObUlQRFF1VUVrOUUK6WUULCzfoGm0VZxhfkK+8KV8Ax4Gksf1
            jtl+RUkl94qZYe6o5NW15kd3cIo4M5qPUtR7g2ZKiEUkQ68B9+tKbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T21:19:31Z"
    mac: ENC[AES256_GCM,data:8Mo4tBsO4CEhzBsgH2lh0KvAQiFSug47rLtcnh82z3AeRMLPb/Nw77W5GzK9/XBoocp1ZfvMhmvr/r+9uXt9yBJohlfCDYtCoOrYQAfOUc/Y9WnJQMl8r5qF+MOz1fCqutV3UsDu14y3+0rzYP24sd6gmJdMSr2CB6DT6Cr442M=,iv:hLmQi1yNp6daqG6hlwVH+orMWUoJEDJpJojTOY0kQq0=,tag:r6HC4ncO9XMSliYpD4dPNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
