# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+O5YbZqtZXKz21pvsMbeb5OIGrdwUA==,iv:iqa1Ul9o+KcZVmiKHYWkhLrApehlKXcPFXQNp93znf0=,tag:UpWrQh8UUKMNNFTjcbWv4w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:9e8+K15HcfC1vMJSBqgUUktcBx347xxxqVG/S/qqjmD5qkZyuA==,iv:Wrjf9Hb+EclQ8ysK9J29ESKUbzVpq9yL85iPUSUe+74=,tag:xGMlrvw8mVjMo352SFPP0w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:r8pIEQLedzWYxw/2+bIb/RqD3qw=,iv:7wxumMwLORcFTP+3mQpE9d0L97reTtTCMcYG38XpiO4=,tag:tchz2jvBP5d3c3Vzl5hBXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRFBKbnN5QUR6dXBLV3Bj
            TUZPS1B2Zk9zM3Y5YjBSaVB3OHE0QzNQNVZrCk9IaGl2VUlFZ1MyelBrK3ZyVjVY
            UExhaFUrQkJhdEYvcnYxNkI5ZDRHVlUKLS0tIFJlYm4yd3YyMEpJREw4MUhGVnZl
            cEFLUlBpZ0F5Z0VDN1FOeEZ1c0NRN2sKqB0s+v3R3QtZnqS3XQXh5cmZDCHmK6h7
            z6UF6usJI/eJEKfaMghEBJZRsAu5NgRGiaiq3hQ+YeWN1ecIjBUyLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T19:14:36Z"
    mac: ENC[AES256_GCM,data:fZfmxNHJ8q5V1Z+N4x2cuDYhw9iJ3aSQ/M76p46qUBM+bf+Q5p5ub8ZoXKXmrOXFJJzzVzxEZTgOXHOINxQfsfM/MfmYyjharbs1F89M/2UmQf02HGcyqLTULSjNHO34PGEH6l0hA21DiXv0e2Dsh45Ozf7cCAp7WhwsgWnCPdk=,iv:olML4CuKRSFqjYDNnl0eZEaBbTZVIK2vwADxPkAl5yQ=,tag:vpnl9xGqgok8M/+yytQQGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
