kind: ENC[AES256_GCM,data:1SBbtyQW,iv:N5sNstkb9MizE7wLqo5O/enknOQtCv0rPOumRCLqaqM=,tag:EqpWwb4Ha9vU8FK1xzR/vw==,type:str]
ansible_user: ENC[AES256_GCM,data:dxdjEPdO,iv:2v/hYbTSH7J++xi5tFcwE5BlkCkvsjHG4oIunR7dqVw=,tag:lb0Yx2fJamS1x9x1a/efcQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7g0SfjQ1rVSfi+JfHOa/e8GliQ==,iv:PFaO/4QsuVyZUUSQF1XMvSgIm5y2Xm/Pj9gBV/cdIPc=,tag:wCQ2yr1WZ/tcc9VOhsjr0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocmYvNDZsWGh3U1hPYjFv
            NHlrVHVmUmswTXkvbXptRW03d0IzQVpVNWtvCjVESmk5MlVaTlE1ckExRXR1MFN5
            Zk8wdXF0UzlIVUEzUEQxVXpPSjNXOTgKLS0tIFh4bWZYVjc0YWhyVXd5R2VyaE4w
            b2p2REIyTk5RSW9neFl1WENHRXNOSE0Kg3erdeUmUpgOh3N+LKSGr1vZLqoFt5ZI
            dhqyshmJrrCOmRGbEAAVraCrwJH3pjRmVIsw52S0xmmxnz0aXt5BhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T11:23:16Z"
    mac: ENC[AES256_GCM,data:UqxKp2DwyItduXtmvXLGgDO8+8blsXgXlxgXXQEnEK8bPoSk3B+jLujTSkIJkOX9d6qt2ibSt4bpM++DcJcF2taDq9q+jAU7+2WMt72ZHB5MEKGOsEyCXwfci8Z43RKi8MBOTttfF6ZiWjuJslUfmayomoEsd5UJdYn4lF4yUC4=,iv:SNAt8wDMxk2G3fu5IUJHoQYAvTXSOA8pC5AXzGjDbKI=,tag:Hal2RPkdfxYlWPbLB9sc8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
