kind: ENC[AES256_GCM,data:f25IRVJj,iv:uHpzp8zVfqJW/h3o3rI1toeNOiq5h1jzWL/Bt07+6uM=,tag:xhygeyZMGbukUkBwdkc/Uw==,type:str]
ansible_user: ENC[AES256_GCM,data:1s3QC9AM,iv:iTRpHegbKIPS4n7hVg0hG3EuqqEs7jE/RFjSiTi8IAk=,tag:5ACBDclciNq8f2gUkRzidg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5ybCEcilK/+g/DW3FXQNQD+f/A==,iv:+ruGsBPch2OK3zmkLZoYZ23emBBKJ0scQw1Xlbp2REM=,tag:dFgRd7o5QmdweX+douHbCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa2lFeEdaTlB3aGI0RGht
            WVZ1YkFQS0RUMFlVZUYzQjN2V1A5K3F3OUM0CndUS2pRWTFKTWQ3MlBJbDlaWEQ1
            NnNLNnh4NmVVK0crU2pNL05icWtSQ0EKLS0tIGlSVWtSYnA3Z0YxdjV6Z0N5K0hr
            R2pGeC94bkp3M0pQWkV1dHppQWp0V2sKv1QsZuaR9DGiCbNhnJeFbj/QjYMKVsye
            Uyi3ai/HN7qauYkmT0Ui66M0j0Akv1OZnKzDLmN3g1J2zRk83I3kcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T11:44:46Z"
    mac: ENC[AES256_GCM,data:YnDzQv1wEZYkAthJuKxmtMmvLmPBQuCQBcBHK0J6eYbinTzHID4ktdhYK46Zlr5BRDkmqFdYz/O6azymMcoyV0m2CasAdbavxK0fJsaiqE0uHf+i5XyYwrljuhuw+wCcWJ6Cr8c/ad91ytS+CWSmAya8HLiUvwNXatvp1F5J73I=,iv:UGjqW51UuOwLeq+EE3SUvm+o7vnROJ/jc2d4RZJfotI=,tag:qefttVYK+1n6bwv5WypX3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
