ansible_become_pass: ENC[AES256_GCM,data:Kx70YuQsIW9J//lNaX95c29haA==,iv:daY8moNnxl6pTCPH3Zq037rffscWZqQEQsnCLYgLdWw=,tag:b7RULxYP5aFP6vvuUrbx0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRUFvbWlZZ1kyMTNtUFFk
            Ty83N1k0cnY1UnpseUxSa0RqVzk4RGxNdVU0CjB0UHF5SFRtT2VVNEkvZy8vMFNs
            SU9IODZpbXBySlFjbUx1QjdZVnkzUE0KLS0tIDRwekdSVmpQR1ZqSU95U0RUcllJ
            eXozaHFLanNvOVRUNWNjMlVncHdqc2cKrnxsUbBiQ+3eYkF0Z5Lb9xZNDbdWfrNw
            kiWi2PquW4e80/OM8NxqIr5dzy2uovEEjOj3YHNqKhw16b5vN5DsFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T20:06:09Z"
    mac: ENC[AES256_GCM,data:7x/YeDTOkbl2qZlIB0RoACuuOLHzyzWGv9id7xT3pMviGdN1/y28RXCiSOXgYqALJRe+r1dzq/m0Pe/gCFeRSUTSf6aVrEJ4pyLX1hDIBSnObS2w2lMhlBV8D1843Cj5vhCjdAxW36C+3regf5yl/bFfB61M8m4eIrm8c1UF3xw=,iv:xbAZ41iKYewUf7uQqz39DllA/33ebv2ADUTi09c3CEo=,tag:nO7DhsPoA8ceWksyWNHvmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
