kind: ENC[AES256_GCM,data:nxkL9icd,iv:xdyK4uJNGF4XaSc1OMCaSJxkOuJzvAVs65ehlh2ZhAs=,tag:tUjXDiSAI7qUhUdDdgMmWw==,type:str]
ansible_user: ENC[AES256_GCM,data:TbfBwQxL,iv:bnXr+/XdPh5ftlcS3cb1MSNxmRvwiOgPk66Ft3kJLG4=,tag:Md+O0hKqNn727yfAG0HGQw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HvHfDiKunzPl77v5oZDPqLKNGg==,iv:0UtFYVsvmhbXnmWyqZyKDqqyWwcjz/2Qc5vXZNsNDyQ=,tag:cU6mS/s5sRUZMhszWbkznw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTRwYUlZNXlnT044SEN5
            ekJmNklXYXZkb0l3L0E5UnY5cjZkSjFpY0VRCmlOc2svM3E1QzlnWFppOXBVS2dH
            OHc0Tys0eXdwbXl5R3dtcmE1Y3dlekEKLS0tIEdEbWVVd20xOHYwOXBlTzJrSVdL
            a3FBU09Bd2ozU0dkYjNjdnFLRk1ZSFEKsKInfceGbSFXBHDpVLMm0b9FSeQKKOLV
            ZVyI3Ph+uk2mQYcDBKKVqsWkwCigXCNIMcCMWWPOtU7qRiJZ2psJqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-09T14:10:52Z"
    mac: ENC[AES256_GCM,data:CmPNnaDPZiCQkZ3DNCr65MYgwy30gw8z+kl/HiWBuPgyVGBSvgjHZfioswTg+ABSeg5gSdRt8E7clki9buiiLXodc3FMDZIBgjzaa1qftuNPh5TzvUgewPtlyN0xuZCrCl2cQ6iEPLvUa4v+yiisMgshPZ2tIR9fxLhGjELb03U=,iv:/kkIvcAYZDFQWMYp8E8Tz5Aq+uUJuzJ47QSMrX1u/dE=,tag:6tB3v9qC7iSNLVsPFU961Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
