ansible_become_pass: ENC[AES256_GCM,data:np3r9GsgB20WVtlnH2U8PdwAdQ==,iv:gRufqQcg0WI6kzlhiKARlohbcy1xmNQ+NReaTszw2oY=,tag:U2hxfPUWec3X2kZWwEO6JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T0NCYlJGL1llcis4Qk1I
            ZlA4YWtzcGpvVFJHOUFOS3JDdXJkWXJWd1FjCnJOdTZrbXNJR2lqTVZPZ2hrNkR5
            Z0RFM0RZeFhHcFM3VTBFVVQwNjVCdmcKLS0tIEROWXpZTUV6UGlzdVdJYStBU0Rr
            Nk1zeENUU3B2T0Zzbnozb05ZQUt4WHcKUQKUcc96dwupB/+YWvcsktB5NVROsoV2
            Y8u31st3+hy7hoeRd/5LEN9a8kPjohDaHSmRW15/fSZoCH9kVotnMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T14:23:45Z"
    mac: ENC[AES256_GCM,data:nuVBOZcw4E6vMAfI8FBo3d8HEp9e3vjzo3APnWnypBpPICbY8jif5gDAw1YJRz04DGRlAF1QwpMEMw0GjbI9nBbuyq53PcZSDeA3T6P3RbzqqIg4RR9ro1tGYN1huYtSpOu1ZmfAkDEyMWuCfXUO6/4Mu9TDeSPra/yV+mQ+r6o=,iv:+2aeJ4IstDRvrnyDbu9dKj6HrW6FYhkwAdg1rdaxoEg=,tag:oiNb8Sg1pKYAzawM4473Bg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
