kind: ENC[AES256_GCM,data:X3vC3bE9,iv:wVN1PpbuS2YLUJSSIIGGuSkG1+jgdpbIkSEdd8awPq8=,tag:dGuZdNXvoOTJ7XnZIV/q7Q==,type:str]
ansible_user: ENC[AES256_GCM,data:IeLsqqRy,iv:BnnjuaRx9hW5vwsGniYRfGYB/jAowdjPjAbvbS1vuqU=,tag:oHG32JXFM2z3W0hrOY6ORw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:yWOuTLtjWkc2GPV3pl7D+sJ5sg==,iv:Gmekt8sbFyJA3S0tOsrPZqTkzxmlyGQIblNEMToJEjQ=,tag:k47pKCGhEMkPhmSqeJnTVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT29ERnI3OWxRcVU2SE9w
            Z09NYXRuTVlTam5VSXBkV1lqMHlnK0RZcm4wCkVmMTAyTUcwR2dqekxRbkgxNlUy
            K0k2NXJmZjZtSkdRaVo0djJCbnI5cm8KLS0tIDc3NEE0akdGT2U2dmZJeWNjZVU1
            eEQyVHdXTVVBNFdEaXBEYkRxZSsvNUEK+JqDY5pBfuUcKAXyWyp2m7RWEAy5f5gy
            RE0Djjxjv5RQO1d2ZXtJOU9RBNp/SVix38S/LBiaB2Ggp+vqJWpqXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T12:20:19Z"
    mac: ENC[AES256_GCM,data:IjYGM1JldHk2CIJKnTmECfREy5x3rHhFTCx9DzwPcuOmPcTifjr6fVM0EAZJGAp5/KoX9koqHpuUpxPnlrJkBNL5P+2/0qyDhBUwlXFmDIo4Hn3wbHH2TI2aHocj0mM9NlDHE+XNs6s8pBNHZCrXnYGOQ8Vpypj9ZFiENVZIuZo=,iv:4aB3mqz6n8T0zrtABGfhLG7PyWMxcy2UIRlbPfD/WYI=,tag:+C8kxK6h2saQ6/3JgasIKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
