ansible_become_pass: ENC[AES256_GCM,data:/mlyriowNfITWO4FhWgjrQMylg==,iv:k6ncFj/ZObpX/wLoyLNgGKXyZ0cpoGUznVbtc+FMrkY=,tag:abAq+85cqFrcsrsmzrTcnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMHZISVozbTVmOFhZYkI0
            cm1CRE04MGs1Rm84L1RKOG82ZnpQVG5mVmlJCnJxSng1dHFCTGg3TXJtcGE5Umsz
            ZWtRK1JFSk5tSC9YY0NKaWlPeGwvM0kKLS0tIGJqai90QmJHQit6d0orQ0hJaC9j
            dkY5Y0U2Q0J4TDE4RE1Hd0ZQMFd0Z2MKT8lrkhgMNNXQzy8/wWoRPdcfyZuuyxAZ
            +DBG7/Wu8N3cniUDQKPg9nePjMgS8S8KANNzu8KqY+EV8P9KhDWOJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T20:23:49Z"
    mac: ENC[AES256_GCM,data:OHa5PxyDvhAmx28GbHyu6RT9XyrOLGBsEMzNtZt4ifCUMnsE7WISi0waQrg8ql+I+LzgTzL9GNJdp5DFJdp6ud5S4+yoyvH0SiVsmpV/G119O88YWoBjx2W13DVGgaah2d6WqxKSTOb8wGsqoTGq6QGuNgW8YK+V1cj6+e1CKxw=,iv:esMazwqAIrK0UId4H4yTPf2O2f1BwkChVE9nS50K3/k=,tag:QB35ZFTXL14D8jTQmfO6Wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
