kind: ENC[AES256_GCM,data:wQdE0K0K,iv:e6zzrEulkXCTJtO9EoACqHYHWbV/0/GJt72QlUs+WsY=,tag:9Vme5JftDzqhQi5QlsDcmA==,type:str]
ansible_user: ENC[AES256_GCM,data:2JFHUD6e,iv:HhgP1SVt/EJXSuejS7CSMn58W3hKXaaPEyidMR2Zm2g=,tag:pFA9T9BeQVilJPTzOGX4WQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3OQDaETtFsG/AbT0miu4zjkldA==,iv:nfNUHRbgownRWCIQ/Sbswi1P1DzO5xtv6/GbZJsfkyI=,tag:JewBg1ata+BM2KCj7dhqSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNnFaNHNEMlV4VENFaUlj
            V0hkMXB0VFdrcmR0SlRhZ2ZZbmJDaTRGSXpRClZ5QjFIRDlNRHROUzRndDVoY3JS
            d1hVS2ZGWjlJTU5UUFVTQ2ttdWsxN3MKLS0tIFdUc0dIVy9FVDFlQVlKanM5b1NO
            aEUrMDZjM2doU3h5MitaMUpEZVVxeUEKIT1CHTKQM4GJPWUbB0oU6m/KjLZNoqOC
            1Q+ZQjuBTltBb1hZOS+uN51owuznStiXepaBAc+0/WkndL/fuTwP4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:55:33Z"
    mac: ENC[AES256_GCM,data:dbbkMJo83lTiog3Zu+xmmNaRGYi0QYlK5vxQVJZ2T40QbBrs1Nma1u4wR3hlk7TEV67F1wNX2NzUoShUVJi5FktmnNPi5sQwPNjjfFKJVclxxbnTai6wRGRTCCQ6gB5axSlEKcGjMt0n0Kby/WH3n02iPl7x8cVyaiNi1ss5+5A=,iv:iFHeDtQFC/MUDdbNk1Bgu3JkAgndIt1HGBm6gAmO/TU=,tag:UO0VJ57LFaJE9ahziulRXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
