---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./grafana-charts.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery-charts.yaml
  - ./prometheus-community-charts.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
