apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6do4DWk/baBObAPgwQ+RzOe2bGjQ/AK2jbOAmhEasuM77Bcw,iv:aTUCabp1voGXAAbvmADgZRPzr2A9O1UQSIAEMGH2b8o=,tag:+1zdt8WTgisewPXxZRU+sg==,type:str]
    credentials.json: ENC[AES256_GCM,data:g52zRXv2EVUoRoOY3uv5TkqHML8gPzzWVn3L9quacohDzDqY61JE3IuI5XjytY+z1pHB+XTLU4KJzqZ5lHbDQheXhQ8tkD3h8xi4qzdJAyS7kOhmVwOyd8H7UX96HCqrXF865n9cOFX2N0a3JrWfo01Ia71vc2XAiDu7PRpFd7NpXTviCdQdvsbeOMf/nquWRh3E2r6nmy/wovOgkTeGBWJj32istCX5pK/fbS7CSQ==,iv:rDEIdMN4sJRx7efR3pxuRqe325Zlh8zYwj72xxL7kRE=,tag:p0COQZaQYX1uCjlrEnqbOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVzcxd2o0aHMwbVpGRkZF
            L1hrZWZoV2taM01OQ2hRVGRmVGtZRDNybmhzCjAzS3d5Y2hpdzlqZWVyb1BDRGwv
            TUhwSVBUOEN1d05FMk5NbnlhZld6UXcKLS0tIEdhSTBBY1NOQjhweWRiSDA4NVA4
            cEFzTTlOKzVReHBuMEFBbERHVlJFbEkKuoPib6fw0dRGoaz3LqRxWmOUp+irPXAU
            p82wbwTGdOfTJR+PwVWjrjrZK4fZnZ5b2szRTyJRw1kJOXtbDo4oKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T19:25:08Z"
    mac: ENC[AES256_GCM,data:+PIEfcgCohkGn0WKNtWdioTzSsMH9vdxdB8+0v23yIzDz4v10iN+fqVGmkPTQrKM/EUp29Smmn8v6hXKYpLFwgeBJWm+EY2Qi9WHf94s4BczF7Ovyl/75QZAkGj8IZDzl9m0kvB3lPpyMMDeaqrQxSl+1uIu6k2waPcTB7zIv2Y=,iv:12uEbN7zGgbi3OiZIJGd7Aafa9/c1jU3eA1HjjRNu44=,tag:Rdqy1KBrG3mm9c7HB73G3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
