apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:/DNRL8ckJ0Iw9tKlgzoPaiknPg==,iv:g0Lm5N+S1DmQRdchIk/KDSvsyyprK2xIPYrcXHG2nnk=,tag:RbJr4DUaeX/805eGE/3sxQ==,type:str]
    admin-user: ENC[AES256_GCM,data:XUY4bjI=,iv:E+j+g7q/T27+NUMNY68eqIXLVN/FpJRu5T58K2QfPVM=,tag:bHOy4G8EUd6FFbv3TziXVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQjd2UkNvSFp6UWc4Zy9q
            NWV2Y2grUm5CcFh5WmxwYU5icVA0aHBFLzNBCmNrbEdURVdCdFUzM2tlUEo1Q1JE
            S3NkT3VxaHU1RVJ1T0U2bjJjQUFjb2cKLS0tIEYrenpWc0JBdFhPZXY2L0dYZjY4
            SG1hL0RzRmtVVUlZQ3ZCTlBXeGV2MXMKHbLiyOv5PVf0q6IE3rMEsReOouV8c9si
            k2HZ9oUbZ97tVYV9klLHGdx+DuQll3VEO/OXn3YiyLkApyoPaGBeDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T20:06:51Z"
    mac: ENC[AES256_GCM,data:JFjjzWN5sXjNv3i2RUawKb7Qo1hiboTLQlQhA9kJF/tdeALYJGBU1nrOau7kSAXou4r6YPTuEmThyEBnVyg03ZGkTISLMnRaclbv3JSNbpLZsfyfp+pW1Ca/jODJL1U9iStXR+cNnQUTdyBXBlr2s1Bc8QWwZp8CPa+hz2Ov9Vo=,iv:ApqYNq+BE3hiP3OUC8cuEWdAZ4IZG8KUOzbrU5Jy6iM=,tag:5y4YUwcrm5XO8UW2/yNeJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
