apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:WwqKtY2C5SZ1a/f5mYm0UbKhzQ==,iv:pXPBnPlPTLDywij5+yMWThf+rMRq5xDTJunz62F3dbs=,tag:MqGdZuYoDNSRSbkFOR5T2Q==,type:str]
    admin-user: ENC[AES256_GCM,data:dDPWjTY=,iv:/slf3do19ayEahPbLIHENVDr6CwhF+v1KqJ/AEkgXoA=,tag:HNvpjbzUc2C/mIVcY85pzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUGFaQTg1S1djeEF2cW1l
            RWNzb2RhQ3BJd3JZZzJVWkl6bm5aajNMNVVZCkNiN1hNUkFoZnk2K0JFeDgvcldX
            V2FYTWpCdHc5ZUtNZjdIWFpja1R1K2cKLS0tIERNMTZmellLN1hYMnNiZlJqczZj
            RzNkQk5qaUtUSUgxOUxtUUlDZm9maTQKES+N72LAXpLst+iHEABtoFWgjZb4Mi41
            WlC8oJyMs6uESFDkS89R1MXUDE6UVp187ePkaeywg1Jl/fqnJPY9CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T14:24:23Z"
    mac: ENC[AES256_GCM,data:ayrd8hVE1ci9cSt6gspIUzCctESeRUcXwFmLeWMC5DFh6G4zN5sZmIP1tofjb+ycRI2LvbsAHk0qDXfYUHEWvs5nFVjgvuUQt+KoNi6TxNlENCjnvAaYvFiXBaPze2g1o9EUmvNqbifPZmLo/xnXsbigGvzGeNK7fNSYdJhpbpg=,iv:rDtf7k18/KUFLEQ/ruDg+UWgSkXAJP714pUWOj24dNI=,tag:eYpN6EOSqozZrturiz3rdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
