apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:sFIQWi5tq1MYGYMSNkoHO/P5sg==,iv:GD5B7EFfZF6pRcGlcuROrKeaWDSsOFURzv+Vs9yGANk=,tag:rIOKBRN1GxkTS2mpyX/Z9Q==,type:str]
    admin-user: ENC[AES256_GCM,data:hqaC8Dk=,iv:6yGFvjXpr79wHjtEQfGTT6+rmn9GD708zBF1mkHLyvo=,tag:rFddmT9Np56wuDK/s7UPDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWWM5UjNBNXpjREZicVFx
            akVtcFZlU2ppazhja2VPNXFHcDF6NDlqam5BCnJyVHh2ajhFV1h4VHJURU1XM1VQ
            eXhMSnNxSUF4RWlJOGNDblNHZkNlS2MKLS0tIE55cDVDY2xyZGpXd2FCUHVlaXJh
            VFA1ZlF4OFBjZXRheVlGSU42TmhaSWsKjHO9CFjJw/+Wh88uiESMfas/6pcW241i
            IjbnFRTcGnmph4JMpBZvz5avujdl6u7+hpJ7yeovVMmpM7GqbrP0/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T18:43:30Z"
    mac: ENC[AES256_GCM,data:QI7yqHV+uPbBwn4L54Dp/zml3S/QxxCU6+n0E90MpgHoR3rq+iClkSlliyNdnzNttYkFy6la4W6nb9iF0yBaH+8o2jk/S2FD24d5rQgLCHqXjxv7KjM6karAW6V8qbpNVc27hwUOu6wrYA5PK/nL0G3R74TUdWCy55RcmrYWaKQ=,iv:0TseUm292GFnq/6QSUcUt+Adve06yUkyFLsjQh1Cb/A=,tag:OSIZP0fJJmouhIVd8ZkvuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
