apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:JsEHFo6in1HNIzgkNgpGY0YAIBTHzYRi,iv:z50fP3eRAcCd7NOUaWKlAdpI/Arwr5BLwm+hIrhvLtc=,tag:ztLJi4naNfUQAXyuerBxNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTnBNZlVYMWNqMHlsQk5E
            eC9vOFJyL042ZW1kRE5GbE1MeVlvazJ2cmk4CnRpMVYrcGwwbDZKZUd0dFJIWWRp
            eXJ5VSsrTkppUWd2QkRYWXdEZE9GMEEKLS0tIFJCNGRSSUVDVFlsYURMUFBWZjBW
            YmVXb1BiU1l3aVc4ZTNERGtIRE1RbTgKDnxjxGaBW1w+HUShh2TGpztqVfleKdex
            JYcsuyF+qNgDdsbyzWxYeA06azc/qZnrnDJBPsA+9F3NNaps3CJKpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T09:58:17Z"
    mac: ENC[AES256_GCM,data:HYjsn8ytAI4kiqT9a9NFpjQkcmvwsVylyM+4PbbKGb3Zjdu5GDZbkUjR1oxTpcW9S8M70z9lhqj9m3Lw2IVGT8UGQcJMyUE1MTWpmSJRAsULW03YkOSE8ml5pOkvUHt/Ne/t+acwEzvHk7Lm51Z1NZbuZWCxrwL80fg9QeR+OKk=,iv:BSJc2XR/B/X1AL5kLM83589tr1CLvaF+I1ApUniD0MM=,tag:JtUHlj0x81D54Pz0+6JgMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
