apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:q6FnGRfK8P7DPbTV6F5tcVXKb22EjeHgSSCai1j0GueGr2LOsYG6Gw==,iv:TUGR68UFOS3XIEF0HLApSayoXALKkeycguC12Mt/nkg=,tag:h9Hh5aDh9DtWo45eVUhhgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFNJVll5QnRxQjRyS000
            bnhwejNUNTl2VjhMWEl3dlZGN3BMaHN5VG5NCk9vMVFLVkdiT3N0V3NtMVVqNTls
            NndKT3dvZDM5SDdoS2d3bFJYcnRmaUUKLS0tIE5WUE5OdTNORU9SOTJqY2d5a2RU
            di9vYWFwTVJhYnlEWThZUGFEUFpTNmsKt8Seazfj0oA+gCCFBPOjLn12P3ovrUyq
            tS2fGSetDU7bOvNsHZNmZsOtIGzm4VvSGlasSv/bG589AnV4ZWacMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T11:44:46Z"
    mac: ENC[AES256_GCM,data:N5RScjCuOyd+ktGOykX5SqE4aaMzhxux/Wtk3CTgjN7Ae8jdTjLmWul/uNVN/8TKJLhbdhVFnf2i6Z1NykroM5QkJfxf7jDfmxGqcadbLN5FU+pM57E/TfNWWcKhhVPYxRsDAv1/gi01zHdqH2aM20znhLpqugjOpvQ7jO0vAM8=,iv:GONcrLnwLQckmZ/yAaBaeyqfJMoqY264Q5h73iod0xE=,tag:W165rGjhqRo3RJAKjUVBbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
