apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PTWvdGvTkRyLmbFB5/xRPjpHI9tQKpA6cKyaW2OMSpDcC118ivuZpQ==,iv:TJVrA6MrHaGpRJeaTIcbAva7/3gJC9xVcHNr4kKGvf4=,tag:5c6KwemhvbCZOr1NMDY+BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZHJ5RFdHZVQ4bGFzRmM4
            UWN0bS9DRldUMm1STW8rYkdEcCtTaThYWkJvClF2SUVFdVRKVFpreFNWY3pGL2xB
            ZVJVVHpsc3lqYy9rVjNxN3R2THloejQKLS0tIEpNR2RhM2IxZjFPNDBRTUg2ZHNo
            SWU4NWVNdUkzQ3FITHBQSXI3TmZrdUkK/JWNXnfrj15eMRPG+91RrVu4y10lFulz
            jK0kFMs/FhT2WTsTclJ0fWF57nPmY36gAhFRDGStiAlOmh8lTou+jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T16:34:22Z"
    mac: ENC[AES256_GCM,data:/KcMjLVJsYgTk0eLMOla3pTdz0EUbHuhAad4s9kO5ZpcaU4e6wbXonA8SUK3CV680i1RQV7otWsHuN5PcnYOFMSpdNoGuxlykiZmtaMaU9k9yObvZcwwjVHlZBIj98IgvlW1C8aCXIjLQbL2OmT5WYjWeLoMEfQrhiEIJDRUlaQ=,iv:gaddvp5kk2/Vs9AiOOqkSQtWCoYT4NoIGN2dos5xMaQ=,tag:Go8ilSw8G1IUvTFWkGJCXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
