apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+oB09BHWtv+xcmQ8sscnmsbRnZwm+acuzO/P7mvEVaKeqQSYL3sm3w==,iv:QfuD05zCeC4tG8A50dDqB4srEyJ5WSECj2wsmxD7xOk=,tag:kairZAhf9e0eLzfEtfQ30g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa0JJcG0yc2UwTzRJTE0w
            K3N6OHM1WEJ0cmR3ZHBEdkh2S0pzU1FHNEFBCnF4bTdNNzJ6emJUOW92ZFNRT0kz
            c2JwWWU3eU1sc0U3K1RTS2lJc2tiOXcKLS0tIEFTRzdJeXBkaHdOQ29XbWNZR1BW
            Y003T0JPdEV2KzVyWnhHTmkxVURKRlkKIJjEtGd3dHyygCLdlaMQx/I+TN2cQ8j/
            2+M2EnbEylUzpIZTiN8tik4+4wi730sl/OYa34iXcNXRk4RD/Tkp3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T17:36:27Z"
    mac: ENC[AES256_GCM,data:Yx4dSVGoNcfVZ5p0QRKyTyv+k0Y9IjF+Ms4xIQQmE6w3Fz3ZYvmc3KgMdsAvilPhwOxNEhkn+De9QaeWK3EUN1ytP+Stj+iUjDS+ekRSXXjJ8lOeXu8Z7hQHf8PueK3Uk0u32fQYEDsVonudTIlegU6ymOQ5WXlquSmMiTvjfZk=,iv:iQDLOR8jg3TKQ5LT+bp30ep9pntjAQU4kTbCXA/6vsg=,tag:i/gkKg5hDReei9WcH0gq9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
