# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:ijCl+O/L+jbc9ItEoLAJWqV4ISaHSoNA6oh5rXn/7VEz9xGzbw==,iv:qaBx6hwN2NgP0VhVBt+jjmWVRDFl3+Aa+65a4p1NRz0=,tag:BiSGExPAuxwvjeVOtSSKjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaWpLVkRKRldqWEtob3BK
            SW5VcUtRbFo0aFBRWHgyUDNjS3EwK0YyRUNBClJKQVlLa29zbWt3UFBJQlFQT0lm
            ckZvOWtkdkJWalJQWXdMdzh3MGtJVWcKLS0tIEZsS2p2ZS9iUEZKNkxhUlczSjFw
            ZGRaTGJaakk5N0FnV2d2WmRhTS9HNkkKzn4hD1NFIcZ7S8Yzx4KfrPgGVLfNpZql
            qArf1X8qH7bf38l7R5ydIArI++A34fnUS3Ma8hLiaz5lpLtD10KU+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T14:12:42Z"
    mac: ENC[AES256_GCM,data:+I8ElGlSzUTqCALIuh4bZagJfeSpuDGmylqc4um0B9RuTYkEgDgw3qIuMv2oNC33/esmn101c1IUcuXpLGqapWFwTYI2Z7fgSCt2BU44c6LU5waVkNvmsQTDpxRSY6NT8sGcpmyyMLv8tAfJ2DxjEQpit16yspXQudl0A5YnqsM=,iv:guivQl0hWOc7e6ODpKNgDyDVHmg31496khTv99E7ppQ=,tag:cEy5sgf1SCrWpud5ALI1ZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
