# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:ZhJ6CfUgZKh5RVouHTS5RNU2tOIozA==,iv:yeGPcfcpP3tKOagvcq4bXsIpy6JSZuC1Fl7IkghAr3w=,tag:KPXGjs4xaIix7cUnAn8mEQ==,type:str]
    api-key: ENC[AES256_GCM,data:4ESwEoiTzlh3NiDc+yu95hT0cro7JKoI59janET27NpGHitdOg==,iv:h9BXhU6n9X6TIIt9Y9xBE58RhXaCYtnIG5sV9r/7F4M=,tag:pKvuH/L3WAztRjgtk3/ALw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cGdWeDRNVTBtYjBkOVQ3
            cjdObnR6ZFB0b0xFckxDRHltSXk4QWMrMlc4CjFxSjQrWUV2bUxnaTNWNXpWTTA5
            QXdvK0xXTzVFNmdkZFhnNG04N1FiUFEKLS0tIHJvRU82bjBnWWk4Si85Qk5rQW5k
            enkyOVZzRXZVdUNUUGJhU0FMSnBMK0kKZRKvcHisZqQ3VgHa505pdAC7qXL+Nqk7
            iwMYADjbG/jVVsqIPt9cKmFYr8PcIrN/BSbd4b1MDIMpO8El9+K6ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T14:12:42Z"
    mac: ENC[AES256_GCM,data:pyEUopFAJcgoGty+a07ObY/F+qJiP5lVw1CV9BRzUasgUK/pPxli9znEGHtXNqB9QSJArLybXQ+KQ0LhMNlA7k5mAi2rLyMYFx+duG1Y1tIwYgx32Cu0MlDuRNJCNE5j2WASxr1LXghJOi56ZCDs/CYMm+P34g5fHNis2R5QssI=,iv:56qT9FdNFYANay3akTXHcr1X6Ur9wnxhWSjH7799ejY=,tag:DHUdLpZzcsiNfR4JvRvClA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
