# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:A6nI4KAiNcYLWQo2YQ0ZcTBIwpvA1Q==,iv:7vtL8nw6KHQOfAv5lXbKJhSTOylWCg6tvk/QOzb0lgo=,tag:gT52S6hvwGh9Niz6bTjRlQ==,type:str]
    api-key: ENC[AES256_GCM,data:rJxSaEaJLpnRS1tsti3+7Znf503rNSKBrKbQIg177dSAGhFhQQ==,iv:Cq0eqvZiRjH684bmogmFMLzNBepcYk9P5mkmP1CslrU=,tag:sX+wtCb1Rxw6zaTdP8fMgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MmxCZHBocDdnZG9iQXV6
            Mjl3am5OekJEc09TTXVXY3plckwzeWU3b3dBCkpsWjdtTFdYWUxFNjk0c3MwYThP
            S3pFckxTcmFMSHBSRmUramtVTDVoaUEKLS0tIGhBTExlWUxaWnVtanY4Sk1HMmdn
            U3ZvcnBrZTF1MGtxTDZ0M1FGdktFQzgK7rFucEOHOtOpPU+4NXNU8Kvmiewhf/3x
            g6tFcjdoIDRTVrzCORP+K4c+eOsjjh2+WRZu860GNyDLerdnppNo2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T20:10:37Z"
    mac: ENC[AES256_GCM,data:T3rggtSe7niYk29uXnAQgGc2AozuwLEtxKJDPsNpOSTz5ciAV1QMhd9H7cDmQn2nnWFEb3BFaq/gTa+qMZN2EC3w+bJcTPuJdibyR8D53YuUJTqhBG8+IJk5szGPh8QIGbYBNLc/gD7bBrYCo7lc88VfUl49+IQoDJKLwWkz7NY=,iv:gzyz8MvO/bjlIggGJhV0U4tjg49FvYK7ShVcP4z+GRo=,tag:/NHXjizvlF94FMhbG6cgkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
