# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:1Alsj20+MbGfgJeTEmj5aT3JR/fA0w==,iv:3GZXiqFDuGl1i1op+/SVhyGBWG5NpCgR5NRpesEHmAU=,tag:WO/ykPkgqRve7sOSIXrvUg==,type:str]
    api-key: ENC[AES256_GCM,data:rODVQJ2TscZTj/8zsz4f3KXM52fa1omJIFj+wZeDIfMX2Cf7gA==,iv:j/3z6Grt1DddZ+6NCBk2IjV8dmm0gC+blArPuUPUVzs=,tag:nJFVhNYfKJsJWjw6wQUeEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArR1hLMGkrcFhSNzYvMkNV
            ajUvbFFJcnhpODBNcTlkSFArcW9yUnYxNTBBCmd2dDJhWmxzODF4dnJzQ0RNMGd4
            ZmpDeFBUT2pNWmt2eTVqNWlDR2thdUkKLS0tIGZ6SC8yQkZYaU52TjdnU3A2TEV6
            VGxnN3NUVWVGaVg0Y0tVcFM5dTJMSWMKutaclyJdeq51YHAJjUCE2qchQa6aUQbM
            cTQEoTCevOCzeiAX5lYfllFWmcjC+nFEv7gKqLwZtsy5P+c8CykbIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T15:28:17Z"
    mac: ENC[AES256_GCM,data:DMAvWZY1PcmWo/gFyx/Bp6QI0YC1dv6Qodhb2nk7GwOFRyq9xCy1BC2VxFJF/cxJHlNCTW6vlTdPwv1auDlWZw4ylFywGQRTvAHMtDsCdErXkWMnXyQosHU5r4eJIu+om5/IEfWqIPCUNV1cclQfKBiLkwmOZJu87y4l/OK43Ds=,iv:k9yftTCAWHxLoNzP6W4hg9tZYHcaBnirRNvxzySqfqg=,tag:UYsOT5/Z9sydlZ23+1F6OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
