# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:ijCl+O/L+jbc9ItEoLAJWqV4ISaHSoNA6oh5rXn/7VEz9xGzbw==,iv:qaBx6hwN2NgP0VhVBt+jjmWVRDFl3+Aa+65a4p1NRz0=,tag:BiSGExPAuxwvjeVOtSSKjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaWpLVkRKRldqWEtob3BK
            SW5VcUtRbFo0aFBRWHgyUDNjS3EwK0YyRUNBClJKQVlLa29zbWt3UFBJQlFQT0lm
            ckZvOWtkdkJWalJQWXdMdzh3MGtJVWcKLS0tIEZsS2p2ZS9iUEZKNkxhUlczSjFw
            ZGRaTGJaakk5N0FnV2d2WmRhTS9HNkkKzn4hD1NFIcZ7S8Yzx4KfrPgGVLfNpZql
            qArf1X8qH7bf38l7R5ydIArI++A34fnUS3Ma8hLiaz5lpLtD10KU+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-21T10:26:53Z"
    mac: ENC[AES256_GCM,data:U1Yj1kCcLI7lHZPaDD1wKVsxyIm41PBUJuHsYENz00XTTzd3fbkvdm1KXkN0obGHr3ZebnW/4QehmPtPNo3s9r+5vKZy1SnGO4muHTxESf5CX7Dsv3r3gUjlIwIFTGCFwJoHCe6gTzfyenZyYpBBimPxc8hTWbx5opf3cARPPn8=,iv:haLHqvwtZvIM49xD12RcFpnv4wnDboq7Vy8BsNhpC1I=,tag:hCzaMaRw6t9fBJivnaz5DQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
