# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fqq9tfrak0zj61Kwbs8h,iv:3jIqBnMxyymdPzRkxjNiw1Hr52yBaSlRnshgfGLVnZQ=,tag:a/9w8WuylmBANQfYb+jWBA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:S+CwcA3WD0UK2W19zgKhQv/pDi2vig==,iv:zmXQl/xCYofef9tyEjCAxBt8ARIVMnce2MSzHCYmykc=,tag:Ohn7+wnczF4e82PcGaQrww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN0xNVzF3YW1icDJnYmFj
            KzB4aVNTM1g5R1JXTjhmOHNEc0VmdEVxYkVRCmZQeXhIRStyS0k2WDViNVozVUY0
            Skp1cS9pamM4N1pNM0VkUkl4WmlHQmsKLS0tIG9xTXNtdmFVWGdRTnhwNnpialRw
            TGFnNkZsTTFUU25id3N0TDlZeE80Wm8KlsdaWyAB/M8IldkIDl8Li6Q6iTL87/vs
            YvotWeB3GkWMmJdNwn2p6fMnTpB5fYT1cvmcZo5Ftk39GFS5F/J/ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T15:28:17Z"
    mac: ENC[AES256_GCM,data:HkW5UhUYVJc2ZFC41cqq/KKFFTP+MidIzIPTgkDFX5P9KFVGi2nfRyvnW5SVI5Viq78EVljZICm1LoH1pRTiCHKPi3BsJbOj5Gn+ZQHL2MtEmcCzYIyimR7/WH0m0/GenjQsfMEz2xIGcKkggrJB8iQdj8m1/o8nmys9RdZZQTo=,iv:2i79kWBpqimZ/2jv3U8HB+WuClNvTkzxEUqO1v9Vqsc=,tag:0pRDrLguPNcFUoJwB6dI7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
