# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: kube-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:prAAR3aPp4UfhVDd/gR1JgcfONSeDA==,iv:Q9gbJ1ZTG9FI3fGjeYwTaOk5D7EHtSdWthGKLE7BtX4=,tag:+YcU+M9tlldpy3jOz1N+0Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:chzciCid7wBac8mQqQ/AV1d7LZIv2PEtLPi3vK2NxKUfO06kcg==,iv:IpyQyurhqpQsBaWy8EBPxJKujW0RnVjWeEhYwe+VaEc=,tag:01Pb4gR4wbaNNBpHrl0gLA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:rx497MpLkuTY8HGuPOL6EZ09AoM=,iv:7xctOrzrjRttpwKyqA26FDrpYcPbmYI/WdneOG9n+iQ=,tag:AMVhPcnjr+/02zXmr2HjUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcGgrZlcwc0tBQ056Zklv
            WTN0dzVlNFV0Q0ticVgzb2RKNEptSDJOZEZzCkZhTTlET0ZuRGJtUG9YK2J6Wm5Z
            REJzbU5iUjhNWHJwTktBNjNUcnUvdzAKLS0tIDNncWptamZYYWM2NnRNYS9ZSEJr
            d2RDUmVBNGpCSC9aOGw2UGgxZElmS0kKq7X+JruArxmkE4Hen+mQnOdeoz6j8c3j
            Lf+iivw+ax+pO6tNduy620gPmyb3TMvoHBQkKwtWzpw4zAbPxK2+CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-10T14:30:48Z"
    mac: ENC[AES256_GCM,data:KE+cgYmyjx3XchkkbZdNJB5GJwBCSNdu+hRMTq4Q/9EXzlZ1ml0TOLBvfVBCtLpzLltyUBUTX1m85SpUe8Gm2ukCyMX0iDSq9dWevOC1W/uX0KS42yNHu4UJHSF00jrmr2yVjotV9+sps0woTL4kZ4MmJb1oyPyPtfWRP2bUe3s=,iv:Tk7+IYt6wBMmVKK2mdoNRCtImYmg3acj2gsUmCnU8jY=,tag:sd2SKiBm9C7mjb+naxknFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
