apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:1vg3VUs=,iv:3lONVAylwMMeTpI6kMVhBX7UStr3L/tkHpJj7R1AAdw=,tag:yiOW/jlHy0WF9nIRVPFktA==,type:str]
    admin-password: ENC[AES256_GCM,data:+Bg8rnG4flPOVg/ejyWPBTIUvA==,iv:MJPt0TxkpZyCnvCMfIVTuX8DDsD9HgcZhIkUNmlpCAc=,tag:ufNTOJUY2K0LhjMQ8xbAoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySW9SYjhDT29tdzd6YzFH
            d0ltaFZDMjRHVjgyeDd4QWV2dk5rY2U2MDJZCmlOTGN6TlZDeG5acjJHa01BUW1l
            WDFDcTUxdUVHcEdzOUlPZ2sxVXQvVUkKLS0tIFk0RVJEZWczbGVNVlZsT1pVejVV
            UkV1S2JRSkhGWEh6anZTRzdEQnBWdDgKfSpNp0iiH365Vq9MmaNCWw34vZObxANv
            /C8p7XzE2u27u+XRpYBrkiEfsxY859B/FXU87rSfbdD0dueXqCS++A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T12:24:25Z"
    mac: ENC[AES256_GCM,data:K1GQsHxLIbgiN6dfBLXdGcgh/bDqJOcdDIEythzDs+uyJQJqtxzmo3V/6Q+P8euJzZFvtmBHAjRXy3hQN5Bioqyc2ztZUdgKuHwjcF+cg+rEaHV7tSYc7K0xhe1p9YoaQ/jIAfj5WQ5ssxvMW3T4Iwqcmu12F893yoF9GJfdIWA=,iv:gnMWsB9EX2WPBu6bjoPctUtj3mt9XG657DL1003PlKk=,tag:rIF1Fj1v57gznWOT6xU/+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
