apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:r1qTRjHDJAP7c8IskbgFCYj/myILVfQsfm+GGt4iGtoXkUNmddAOxg==,iv:SEW57FEXMpjSTXCWl/uYydrDfG5YSpnbb6VyWJWIChE=,tag:PA46v53f0eSLlR6USxDiGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TWpKWFNVNzVqcG1MdU1R
            Tzg4QWgyekpBVXpRckRNRm5aWlo1YjlhTFU4CmxUMWtkRk1ra21TV1FMUXdVSGNJ
            cnlTMFVkcjVwTmFKVUxKTi9GNWdteGcKLS0tIFdEWkk2dzZ5d1JKUDBnUzhoQVdR
            N1lXUllMTXEzcjRPNHdkaS9OQlMvdmsK1ezYxK7oCekXyT3iPvuvN9skUg+vnBdg
            HmV+oWuB5QPF6w3qAax/EfBrY6aRpRouqK/J07kUBd/yFIt8muPCfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T18:43:27Z"
    mac: ENC[AES256_GCM,data:Hw2UEg3+Evp6cz55w+7p4+WzBoch9WvcRxZInCr29SPdv5owh8aoBPwUlZNWt0XbX+QO3ZVSe4inr4b5D9/N+UHJxKKcyNp/Eoyke4w1KO/od/a7Z+RIpygAt10Ph9NRztVCZuukJrZ4CLT4OjRaEj4b7cvVAJtGUlvGWHDfNKA=,iv:8zFvmKo65L8iqC3qM9sWNjm0sxcome4lLa+1ppW1FuI=,tag:ExSxdrRKaDUPl9qxIuRr4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
