apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:05OpqErS2WxDPTyxw5DaKrHgNGI1kiLLMeucNqOluPpxJmXjo4y53A==,iv:XbBGIEsmHrljoEZP9TwBmmoJWonVIIQG7nDBNhzeNiI=,tag:MjzyzLGwBgGRcfrLi98Kjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdVVYTXd2dm51MTFKaVBT
            eWRwTlByTzd2NEFVb3Q1R213T2RlQWlvN1Q4Cjhzc1M1dXNGcXh3aWpSQktIN2ty
            TDZuWHY1VkxMdXV5cDZJSlZjQWFGNzQKLS0tIHF4TnQ5OEVmS2VXVmFSUC9vbTBl
            RjlUZENUOHZUdlFsbEkyWGZNRVh0NDgKZLxTLstCIBNEOe0DZ/mRavm03XhxxD4g
            pHrbITNITyqYjG90v0LxSFwUkf9bFTCQ4fhszapWb7oQ1QINcGvZGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T17:36:28Z"
    mac: ENC[AES256_GCM,data:1SCJOx8DKFnzSlg+elCMK5tWKJreaOZGjab7/6H79EKL3bOqS7js+Yw4bg5D03fYqwjxeA1gA6BRQm0vHWAvtmHJI7aLcI5T/o/YHUZeQfSsf+nImL7lyOFzeYX7GA7HZrZpo+YzCiGkESt1zUpA4y46l/8SCoGth2kTo4BNeiI=,iv:dPX+ehKcJXQLNZYGseYfPm0R5KqWcKcFwInJAxN160s=,tag:QbsX2S0brF0b0BGpF4Otew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
