kind: Secret
ansible_user: ENC[AES256_GCM,data:WB/QeCPu,iv:LcR8IGdFRDMJnM6/vXEc+4sPncq+78ojv4mBZeVzVjU=,tag:RZciwAHT/3KmFjhTBfvprA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cX5vBXzPkVmB6Opn9lPY9vH+Sg==,iv:pnQrPym9RJLd7mz4IbTqhn+t0sjUAaceobVrAPLy/IA=,tag:tBdxK6+dg6E3GoYvZ90IjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUJkN3NwQ3ptUVdRMkpm
            QVBzWHE4L0k5ajlzYU1OWC9zQjlVczBsVVVrCmZyeCtDMVhaMW1iVDA1VGNmdlhp
            cFZtQktTZ2FIVk10N0N2U3hKVlhtYWMKLS0tIDN1RTRCVld6WFQ3aDgyVm9rbWFJ
            VG8yVVhoMnJpblhUK3BybjZzYlhsTU0KV9Cizgqhggg1yJ7zFXBfTH2GmD97dV4n
            8XQYwn1IhYR0+hVDdf/WalXmS8+8cKpzwQ33oErEHCM4xyWtAoDmdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-17T19:30:57Z"
    mac: ENC[AES256_GCM,data:21RSCy/Ofzx0n/666JIGhdiISm3xw2JdQD48hU+yDWotf5eVImsOSjMb/l7j9LVmnctG/UaLArey5/DhQVcSEXxGcv5wpzRyNGsM+Jco81T2/KI26vl3tEOSNFl7p1vRsB8LQeJWOxR/lcio95LfVT1REUplCgzIWbR/Lx1jkks=,iv:ixmcIuzUVsDydCAdF71qPuzvaRlmxFlC4ENrcSBlx1Q=,tag:FBMgYriO34ln4bv7aTEPIA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
