kind: Secret
ansible_user: ENC[AES256_GCM,data:xF7qRTtLzq5B2cY=,iv:Z4+ezraV2XaWz6Mcoz+wjm78l0rgKjNFSFtFM3oqE20=,tag:vTwNKhRnBSKaPzfVpYHAFQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NawhGpyiBq2uBg==,iv:gUlsHcJ/NicNbWP4UjlQI/9m2Vr2xHpEaZD9Z1ArQxs=,tag:zBf3cPJ9CDe47DPN2sE3+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UnlZVUFtQlRjeE5ONXkr
            OFJuRXpTZTZNWS9XY3laSFI5N1htT0lFM3lvCnlCeVlqeXVVTnd3cU10MjV3SUt3
            cUJTMWFFMEwzamtBS0hXNFJ2bU9uRm8KLS0tIFI2djJ1akE4d3hRdkxzT2c5ZitV
            cVh6SXo5UmZLVVU2S1VLWHBzMEtYSDAKiX02OSCSiUB+uRy0mDLwfCT8Yb/6FdTB
            P+Z6Kt7yXpHHfEenka3Cvw6jEXabDuzCWqLGP35F1l5BQiw8d37OCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T17:52:14Z"
    mac: ENC[AES256_GCM,data:5GVnno1wRj9qFdoMIFCqLvlsoVRR6+Yie97wqOlFhfj+dSYVf7IQk7Cg/C0v0ZH7POUFyEQa7ezJNd4VSSrc4tnwCTMf2432Mknd9fGbHPxrFqHq9xucrD2/lE5Y4ocfre9zobiSVGThk8DDZ3zGtDr7CVHMkCn+EzAEHY5oDFI=,iv:EB6IqPdL1iHV0rlYje8bfMFyTMnUA5mviJyoK0AZIRI=,tag:SMcILsMBeDb2ggT3w0YX4w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
