kind: Secret
ansible_user: ENC[AES256_GCM,data:LbhLjhWEWKUXUnE=,iv:Yo56zX9XoQit7AT+9Hb7ae6AurT/RtiklZBVlCSs/ZI=,tag:V7QYlDj5Y9T7oH0aESfxdQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KSgjxSH9AojgfA==,iv:4/1U/PNrYbGb+tiPlyt5Mq2vDpG49AC7vfdu7hPoba8=,tag:g/vAvNIceJ7FBkYJf02nGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RktIbDFFdm5lNHliTHEx
            Snp2ckxKN2ZKdzFkWFBtNzNwVVozU3pzUWcwClJmSHJYZGk0Q2pVaDZjL0JNZHlI
            RURPTU9TdmVrcEl4bUU0bHAvOEFudjgKLS0tIEluQ3ZBTEd2ZXpNUTBmbzRHbEYr
            N0JHbkhtcVB2M0VJYTdLYzh1TkZUa3cK1I8EdbrpYvM+sj/f0+dz2MDPgBwyUFAI
            IeDQq7njzCv8C8c1qFqqtZd5jrMcxFdmsrx9JeKEi3qCZtgrOYARTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T19:14:36Z"
    mac: ENC[AES256_GCM,data:Ydv6l3vXTJwykn4gkeZAI2UD8R3P6s6BtVkaRPY8ys3y3wjmAV/7/EOERhhp/DTWcnCYFGqpIxuYCiNB7NCLxssaOLeo3Kaqr120xUF6fufy+PczLEbyPgviwB7safYFWtJ2dQ8P6Nn/eAXr8Xggs2RdVMh+6Ldge5P5elQFIvM=,iv:kScO963eieNO782CXeiZGXcFlYgyhZjagL/B3/59oTU=,tag:73JZxEr3kHx7cEZoBazAXw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
