kind: Secret
ansible_user: ENC[AES256_GCM,data:O8XBvdYbZpx9Lr0=,iv:ogmKuBw4bdVaXwD5SXrtSqSN9epxRjMhRAYqrAWnVn8=,tag:cjWucfNJQAVEAeDU8HDU6Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PiHJRdkWFLkzzg==,iv:LQYLLLunUrCbpBa9x19LZAFhn8FAE6JrVXwcFoyQb/k=,tag:Z392bhcVQZg1GSL+ZLsb1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVV4bEdJWXlLdDRXVUhH
            S1VTZ09RY2NET0pUNHFYT2Z6UEMrYlc0R1hFCmdTZTI5VkFLczZ1OGhYM0wveFdT
            QzFvUmdTYmtvandDRFBrU1NGUkNlVEEKLS0tIE0zaUFLVXJUQ0paQ2s5Qjkyam4x
            Ly9QWm01djZVQStLdHdhcUhvSy9pQncKNvgfCRQPUTAAKQUqHIr0H5sbpJRBlVm8
            Fhpv8hFxNVicQwr8U955g0JCQL1JnBCCJcpTIJuSPVinbne4W6OlTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T17:52:14Z"
    mac: ENC[AES256_GCM,data:sbBvsWxeQE1vtv+/Nlpa64EKNNZ4+XEFxtwDqrklb+Dbhu9MHyajpUt+YV3R3+vEE+OX4B/mq+hv/G6THVNX2qkRU0SDF0aYIHuc1aVT0bprgVRbnvHxn10s9zLJIWtqllQM3lmJUrPv7AZqgqzVopVl0sZCacXnpubFvWxunMg=,iv:7WzB22pEyvUBRKLrRcQ2a5vi4hRUjh0ypf4ij6znoPE=,tag:Fxi49y8g5jjYAelSj1iRFg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
