kind: Secret
ansible_user: ENC[AES256_GCM,data:/7/AUs/CDVBzLH0=,iv:rwFAXZdjVcDqOXkyTIWU51pzPA+hPgRb6/5w2AKi9N4=,tag:pcv21bDHquTajTH123tZmA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QivfnvD6pHvkvQ==,iv:hH5fneYoU/cveyIE3JhrdtE5EKcC59U0Aesxeuu4OTw=,tag:EI3ycbAN0bZq8mKQBzxANg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ1FvZWZYaHdock5GR2U5
            R2JQOGI5WnFyNXR3cVpPRmRnRW5MV3Z4b3g0CjZYbmIyZUNsclB3MDVzVWJQOGJj
            dURrT2hUZWNHNlNtelMxK2pnYnlzZkkKLS0tIFRmRU9jbjVpRVJaOXRUZ1g1YWls
            Z3ZoN0Q2K250T0NXRlZTUDRiQ0lPTU0K68KjrtDn3xQ63sZJbHpiZ0DMjGjuX/45
            ldRoguFxMvMthV4bmOvA3lgyVCBWQ0ELqhPQfGpA+/+QDZPZkWLWzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T17:52:14Z"
    mac: ENC[AES256_GCM,data:XJLWCuNutLF0bddsVvT4wnQCMaCTCZPDFubR4K+jGyZCG1v3CPeqRPQNc4GAmRlU0+lOPv5jnnqhfeFJp3noHqVieOriMxVWqPHdDQoaFJE7uOXu/mz9sNPkCTGyCWU/UoNpWl1tYFF0cosHgeeKxxhSik38bBupyd6Nlr1muWM=,iv:oSiuUJPRs8gDzBIcFUXYXiS9V7Eq3TQxoQ+eNRkG5NE=,tag:rZ1z2JYrxR6gXmhWw6BkmQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
