kind: Secret
ansible_user: ENC[AES256_GCM,data:G8qMH8WZFA3ZuKQ=,iv:nBtG7zLmpVp0pM9qL1lKCflRKf3bLJXJQ8CZXxSLm+c=,tag:Oj08f85BPE2a4byCn5sChA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AUu4Lz4X3CiD5w==,iv:PBwYfkR9Ke/BntTl7NEXLMnukGz91xJ1Xe5hMpAPZR4=,tag:Fg0LgYkJogvpi9j7CN7Y6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwajVOMDF4dUdMN29FcXFh
            bzJocVBFWUlRUGptQkFwVlVLczJ3WTdlZVJNClRmR3lxdUFoZ1F4bHBEdm5IZlR2
            d1BXT0JNdDlCSm5tT3dPY3BjdEdJSHcKLS0tIE1MMnFUQXdEMklPamkzRU9mb1lS
            Sm5INnppSnZqRDdUL0hFWWNYVUpWNGcKGQcRmsmSbe8SXBogynAaG1aUcAyZLSze
            VbTuQtRYkzU0XkQ6F42w8By/qmWm5xnTFf/88rIe/Wx10j3qW8O0PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T21:19:31Z"
    mac: ENC[AES256_GCM,data:f4YeaTwmTMtDxiWPprUyfaQdH+xWLB4/dk4nQPXtWR2Ym+ein4l7foMKmIDscOvoaAhv7gRqK/Bv691jeRp4h352GCC+7LiqQsNyd3JfRagMUXmA00tuy1Z2GZ/QgNqo9/XjIuc18p+wLrit4uhHcUxKUI8r/wYuHAm1/PJL8KY=,iv:4HkioHJhugC+bNMJs4yIxlWaxB/Ftq67LiNG7C7HuPY=,tag:4IYX2oP1A8a1mywYRxkBAw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
