kind: Secret
ansible_user: ENC[AES256_GCM,data:Kdrr1Kc3HrlrDDY=,iv:fRjRQaN+0Ax7G5s3clGzEDb4GIqaTINWHTag2B4qqsw=,tag:TCdGoVgXdVdaRn1vY7c1ZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:uNFq1RWfD0O9zA==,iv:fJeEsmsXwyqLf+eEkhmyj/J0M39NBfpE01myd9/Vfb4=,tag:I5oJGayRHrQMUsITZ+aHew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ3paNmV3d0JXWE9MSzRE
            bUZZakZtb1FNSElzclFnb0wxbUNKMkR0QWlNClZKa0xDUFVVdVlyVGpOK0NmUnBt
            UmVTQTlWc29YQzdsZ2dYdUFsUnJKOFUKLS0tICsxTWlIWnBYWVlQSHJKNWF4S09r
            NGZrN1l5YW8wc3Fzbmp1ck9kbTRvTVUKmXstVI3lsLSSTvTmKO64XV+65YDcQDLL
            Qm/dTvMjxwVcUUKX+qtCWxn4JNYFUm8sbxZEBDtHRHLHgxxd1ndUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T17:52:14Z"
    mac: ENC[AES256_GCM,data:h4eWeAzDeHtbZX54FlZyjRJ5Gh+wpQOm2NRNl9RFuMbK0JAhFMgo8xEDelB+dqqm78MovjVNTuxbA4MOuALDhEKdR/iPAORFUmC4/q7ln7/OsXACHmwCbVt8XeR/UIbSahmijyQzytRng9g70qGRkVA4iTzqSIG85iT5fyjbQAI=,iv:QrrREURfUMJAosP16sy+WrSLMRlR15/tSBbPlZQ6TMk=,tag:mKgdsLEnArA99y5OPyNbMQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
