kind: Secret
ansible_user: ENC[AES256_GCM,data:2bGY3GEGtY0MuA8=,iv:H/WkgohOwBVIhTQ8NoNvveK0ArNp+NXK5jBZteXYulc=,tag:+5smxqvNNzVJr8zDVEAysw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:09O8oUsFoUvmpw==,iv:XsuKkswGdPKQQ/Kd4kqy/R6hSY1LzvPv+yGU0buxm0w=,tag:3lY6jyZoo87jBLJLQBXyGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK3JMN1EvVGhZUE9mQWNk
            VDNjejhYejA0aGhkdy9kdXg2cnA3aXd1MVdJCnRoUGdsRjhoeHowcXVDZEc3eVpM
            c054RTVjV2dCNUxWOTdGTmoxSGQrcTAKLS0tIFBCNFVOaVgwK2ZXZVJUZi90OUhN
            TGhtU2FVdnpWWEFVOWNiUnJaYUYvOHcKVAf0GHuMig3/uceeXEBxQEUCQuNYVygL
            RIQXqDgdX3b+yUhYa0sLGCM1SsRtNEB+jWrXzMRGK9+qJ6H2V27F9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T15:28:18Z"
    mac: ENC[AES256_GCM,data:CbvNctNbjr8Zcokmj47mtV3XOVIfMqObuHS87iZ1x71bHKledkHBVm1yNSA/8Q4J7HUaEi9daZDqmpBwjdUJiJPPbk3DCtNqG0v9hco0rWrQEJLeVDj0XTGJcyspmdSX57VEXUjZhXofHqda02KhvF8DNIGqYQAfHY5r8Ycjb4s=,iv:yNtRfLJlcQ8qWNk1xdfZYs56/i0uWozVhvKndZ6lIA4=,tag:xY3ROMOwdhYSmAtYa5QiIA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
