kind: Secret
ansible_user: ENC[AES256_GCM,data:5kI=,iv:c3aZmC7NuVhdZgmu2k7/hRhRpfMyWm/YUIN9Kr7WhU0=,tag:V/mEeRtVcPoIiZMKIcM80Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QkfsLGeDEeNMWaL8oaezpqjb5A==,iv:H1dYytSWctM7R2yQmtcdpXDoUiI9NV3kHbyxNRXTYWI=,tag:ryP34bZR97i9+RSCLyfusg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N2x0dk9DNFFPLzRnNzNx
            RlJiVnZOTVJiNnViZzZUV0tUR1h1MGdHYWdzCjBBZ0h2L3VHUWlXZDlXTVMyTXZk
            WFFXdEJzUFRseklQWUJsbmhRc0dOMlkKLS0tIEx2WU9PejdsUDNGTGpWZjUrVHZ1
            OGNLQWpQd1EyeXlxSm9pL1FpdVlPUFEKk7NC8w7Or+aPWVcv1+1P54WqxbpJt7tK
            gYDMV1ny9R2qgORqeZL4IDvRLu7LE+aXVl1rLlXIBcQgEWmjqKSOYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T15:28:18Z"
    mac: ENC[AES256_GCM,data:a13Dpxa8gab26Ozs659+13YyZ/NKtAt3jI93WueJs4s6Kvprdyq0f9OAibn5QlNtBN432U2fxj9DOXVBs+otXP2qaTnvNFe1qqUU76Im5+AdF+n0IIn1rta2lYz82NudfRrhmhfm496cTJwTbQ3CABUKAuVT0X1kc6ZUWGXrqJk=,iv:9IpzFLFHVUrjRSEM6An6mM2NJZ0HE8/tWh8VqtdvBZE=,tag:ySOQYYn0pqotnTJx+zdEfQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
