kind: Secret
ansible_user: ENC[AES256_GCM,data:M7V5UDqlM81Amf4=,iv:BF5F4+00pMj99oxwPKKXt3aQ6SCjvsQKaATHVxTUSxc=,tag:kH1I50/ZMm+8mnTML0aHQg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:stUz8QWURpKfJA==,iv:DP9fD0CZmwALHbwsn3Di/iI7hYieK9vkU97R3STO27I=,tag:J+Z+VWXpEi3sTvS7Hc50rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSmUrOHZJMURBRmYrdHM1
            YmkzbzRSbHF3cHhxRFVzUUVMR3hsWUlTRTBZCnVOcEZGU1NMQncrSCs0UldSZUFo
            cHJmbGJaUlliT0c1TDRwa0tLU0JBdGsKLS0tIGd6OXQzc0JPWGdEbmdmZHNqeDdw
            VjVkZVc4bnEzaDd4TFRPdzNUaG0yZDAK8akxpQ0Mm1AG8DHc1ngEqU7pHZsIz5zJ
            rwB7kjgiXQaqmkcmZwAb+bj3Ufq1wkQVM42QBnOxVh9oHHKKrmH73Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T19:14:36Z"
    mac: ENC[AES256_GCM,data:JZ7OQANrE+uV1UZDef68nFwDlHQWFNYvY5bpJ7PwJa44/IaWRoos/qvGYXAPhdzh5EqtNs1mlVdQZ6AOIZvqAGw7kKIN6S5N3CoZ75UKgjx7INCaqdihaLVd2z+t6nah7goY6qRupZyt5RaptEAo7vimFBm8h4Gy9Df/0sQbuFk=,iv:QHdbqkjXKkuRhasRxV60R1SuvZpC1KnARi/wh1aLZWc=,tag:Key6HKNG+JkOwNgFweP+Kw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
