kind: Secret
ansible_user: ENC[AES256_GCM,data:0ZQW+Nxh,iv:tRtryxPx0pvZItn2mdMG+khtzYTnyfSezm6yriGCxZY=,tag:/7ECW3j9lLy5tFkpBKuicw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FQFjd8VjLf+4o9RR5G+yo36Xig==,iv:aVw/B6s2MzWbzB63lQG2ZL3HViSDCI5y8HTrgttYkKk=,tag:ieS7LaBPwep4bGFlyRqUOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN1JvVXR3b2VHRFd1SHRt
            ZzFQVG5hSExqNnpiQzU2Y1AxTHVIeWpQSDJJCjdKbEhJZDFzTXppVmQrb0RPamNz
            N1NZbWt2T0tDb2ZkSThka0ZCSmppcG8KLS0tIGlOZk9oQldUcCtVaEo3SW9CT20w
            dVF1Z04rVjVWZDhIajkwK2x6bnVlOWcKMbdZUXTYrAIs2RoOoChWgDJV3CbMQULl
            /dhXMjxRuJVaJLPGl0m+GnHceszkTbnwoNOHhV0N//PUR2KxTzhBFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-17T19:30:57Z"
    mac: ENC[AES256_GCM,data:yHjQY4IS6CLgHZYzhGinCKH+aPMVdsAtcSnwFJIJIGM6lMAfNCrtA/E52vZtIXmCzX++Sls1MqrGWkOB8GMh1e9LHFAyNkU7LqV0UXpnWuEsF3uBX+uIpgi4pXxvIWr6pBlJEsSQgmS/gq4SK2O2r1aT9fbcTPzpkOW0OQ5rMC4=,iv:PJ8YolVz3Fosws4TRU0tdaxiSPS+pMBcbmaXiIan08k=,tag:HXyofAExdHd3IMKlq11A1A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
