kind: Secret
ansible_user: ENC[AES256_GCM,data:1Icm5JU1,iv:6UURYxiEyfnQCx0bhhKEW/C26daKERbUfjcj4JXlwcg=,tag:7ERkuh0Cp78ccKa9k8fjkA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xFWoobMkvVqhm0IodeTVhbhjJA==,iv:VDCbyGwMCY7PYBLDbsTe8iamPo+Y3gp9rXTAEKGhetw=,tag:S3xE370HxVrUzkUBRT3CbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZy9ZNS9TS3ZnZ25TUGJl
            MzZLT1ZnSmEyUTJ5TVVzTnN2eEV1aEp4Z0Y0Cm10ZzhDNnZNbWN1MHdTcWtoeVFP
            M3NFTS9WOVJ6d0w4aFN2UWw0ZjdndTQKLS0tIExHMDRwdEsvakZ3ZkZtelFnWmk3
            eTY0Wjk2YVZ1YTg2Rll4Ti9pSll6S0EKDTcG64rdHhkmdIy0OLEiyf6SjduKqBSR
            oOiYElCdr+rXclwQvUZGMH7d9BsljEBMoHYZtmifVL0TY3JnD0uFtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-10T14:30:48Z"
    mac: ENC[AES256_GCM,data:qfMt6kuuMh/PTeIzRuAOQenBXJvdo+SNf4sgdL5F3mRHx7TZalQU7vdFOFZTIUivVOlRY78CTC/tQzXrdnKIPviG3EiyUceJRCw6d+iH9xyXgBkT8LffvUx9oRhq8qXoeVO0Hf6twqyuHgiFL7Gchd9sPa++eWdFXW2oBcPdNC8=,iv:V0cQ34LAUnFaV5snDTO3ZQR1P/d5EBQ2K3LhX3W7Hso=,tag:Sg6WCNBYqgDGxZlgQgRM9Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
