apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:wUgabvPTrJ/8MHS0Y1oVifBuWy1qXGQ1fhlMVjtJnTxqbJ3n5Y1mqQ==,iv:YVM5Oo4PYKp1NsBUG+fvyD/t1E+kCQbwV3awF9LOhIM=,tag:KBRH2ly+85ZTvKvMKjbFgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdEhXRXFSNlhPMDZkUHdk
            NmtmeUNLUHRlN0d3eDhEZGwzYTVuUWpBZVNJCmVTRTVER0p4c3NFN0htcW1yKzgv
            Zjhkem5FUVFVR1ZjdVN5MnFCb2ZmbDgKLS0tIEtocTEvSS9XYzJpRk4rWnRMc2xD
            dzFLRldXb055eGg5dXMwMksrSnJzMk0KGEgYZ1Hb36V9CTRFFfqMNrWCP071Dq3n
            YzUfi9rHxD/Fg64Vmu9dZQjLZq6Y608HkLcwFlz4x/BrY6nGxwdkjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T20:06:47Z"
    mac: ENC[AES256_GCM,data:wzuXYTwOSFiwS1oNUa1haH1S2sl+3ZTCuDt749U8OKv7x84EzGVEHahtkyCzMlIIQNe/DIoGL8YPqPLgb96nprPD+TGHw8eE4JcEUuRkMMo36pkAT1c4PDmUA/6euc759Qa/0/OXu5Wa+omUtQ23fiY162KTWLn4c90plVHbwxM=,iv:zdzAz8JoHjx441PpNo4/FFKglLUHCorj/UQ1UPxxMIw=,tag:htJLT3mvKVnuZ8poaHdmmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
