apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:/Q8DvYM8W/wR0YhEhbDHKgX1RbEpng==,iv:rVHw0uFHnDj1edRQ/dWBr1j5yGz3vW/2lHo9ZmCxkeg=,tag:WXHSIldB7XXaDf9kax3Ctg==,type:str]
    api-key: ENC[AES256_GCM,data:QY8qVJNXG3Tt9SJGygLbAG7YUX/ltdahOqts4pqFFqo8n2cALg==,iv:bN9Rm/8kQWaHg3DNA6ejG+o85fIjuBzNthSkb6Zwd8Y=,tag:ZNvkzxfm6tshXnKb0ny/XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwazJIZXFwRTBiWkVveEE4
            SElCNHI3THZGZ2JJZXlNYytUdGV0VGcwenc4ClZWb2Z1T2NhK1UxeVhvek5xM3lm
            amYwMnJ4US9MMlJ6bWp3ZS9aUzNMWncKLS0tIG5Yc1E4WEJjUUlXQ0RDNVhXM3B4
            VTNlaERNSEFldE53V0dvTWZ0cnE3cUUK9Jo8DhDCWYmrtbqVpX9tonTkojw9ao9C
            r+2DCpChCGq9rEhfg+nXYCWq1FUFk/VezRE2LevWZZESYQ5rGuKmOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:55:33Z"
    mac: ENC[AES256_GCM,data:b+wD2nC6pSOuQ6s8JZEltkrjT6tlojT51mwvPvgV6oswx9J0F/6ycBJ/Nz6yrlmLaD5K1DMKN3A+RCbl9WgyzhX++iKvmTdF20PsyBpykRcHLBVIt6QZzNpeklDXuTUV8UM2UJtbtl6XFQVK8t8I83io1/wuvbo7lzFBhmNfzOw=,iv:1ZAWQZXXDUGyYqJ5HuJb3L2A4YlGXTVm9mtUfihvTMc=,tag:BzJyuRJZG9D2nnCyjzmQfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
