# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: poracle-secrets
    namespace: default
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:iYBJJlNrAQ==,iv:22Ma9oYIGXrfRjT3KHpPAEAUw9sW7CFYqECaVBx7B7k=,tag:6++0CQH2IWk2CxlyQf7tQg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:njmnzfL2vTP3V0vZlMzSPTNavA==,iv:vUc7bnwF9AJ8pgTHpDAKwqe99Vdni5VDAyNnKJeEoXQ=,tag:gvWZKdLvSsiOd9rIE+v4+A==,type:str]
    DB_ROOT_USERNAME: ENC[AES256_GCM,data:Vx3K/Q==,iv:0BI7hxz+gTDJDww1u3g2DuVtYrP4c9+xBmGDVGHN62Q=,tag:iAEI74xe/mFFStmIbpjOHw==,type:str]
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:x6fZOZk5jFy60lN/Sc4UNzqC1A==,iv:G+CqP1lLyqFh+pS0lMfno7V4BcvJ3r7tAOMFqFFEpYY=,tag:A1ON8radaiWjrkdWRBF3fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTejQ1djFGOWRZQUcwb21E
            WGNtR1IxdnZKV1hOcXNlUWlhQ2VXbm5BU3dJCkxyRmpBeTFwekZ6Wi8weG56WStO
            NlhDNlVnSWJMenBoMXJYL0thaDd6cDgKLS0tIFNlakpHajV4ZVo4ZnlITVNjN0I4
            S1RrbWYyTkJtbCt6ditmMVdPMlpJVkEKU1sK20DmgKNN7/xWp21x+xHJ/wwW1CMt
            XIim5Px84G2VyaQ2K3u1Xy2VtuJnPKM2KGi4bqyL6AVGAaAv9GL3XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T18:44:07Z"
    mac: ENC[AES256_GCM,data:w09Flr1c/NTdG9cTfJlx0WRkkWIbh1fc/yQf2lEL6fqmSeMkFnC//ME9yKpz9R3QdMh2rYKb8LuYIbWCVQWK4Y8zxjzTVr5dbQ91On/++RlmsyH8gar/teP70DxNhZmqdYhH9LESt4nHtR1DnB+gaA4g3dtraTdxRmToH9WN0Tg=,iv:ne57oI4m+8l787rRLUdgIkOoPqiUFYCuwWhNH7wTY/g=,tag:uY3cIwYk+/5NsifPqIkrrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
