---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: palworld-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/thijsvanloef/palworld-server-docker
              tag: v0.9.0
            env:
              TZ: "${TIMEZONE}"
              PLAYERS: 16
              COMMUNITY: false
            envFrom:
              - secretRef:
                  name: palworld-server-secret
    service:
      main:
        ports:
          http:
            port: 8211
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: external
        hosts:
          - host: &host palworld.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        name: palworld
        globalMounts:
          - path: /palworld
