apiVersion: v1
kind: Secret
metadata:
    name: palworld-server-secret
type: Opaque
stringData:
    SERVER_PASSWORD: ENC[AES256_GCM,data:Hghhe8QUf4TD,iv:tmUzlPWhcxJCAulrEUSMEmiMcn/apolgpuuwvnQCTMQ=,tag:GD9U4sK1aiMAbBo5RaML0Q==,type:str]
    SERVER_NAME: ENC[AES256_GCM,data:cpX4IuI=,iv:a9wuAuQNFLB+2+DbDX+b3FS1bcZXTsJq1GiTEgNJDCk=,tag:IMGcI4OGKJkw/qb2aEvekw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JNZMPMPHuBhK9yG6aWK4xkVzKg==,iv:7ZgtAOQTuf5aUT6P6unQ9R8ErZCMwmX0qggsoDd6sko=,tag:0OvqYeHIVZg6DRmSzM1zwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZDA1TEQ2VG1SNHdrZlRo
            TEN0clpVMmJiaUFqcWdTRUlDRnpRaXIwSlhBCnZoYTZwOUVUcXdWVEFCVURuUmZH
            c3NEK0tNbnpCTG45TWNSTWJGeUlXWkkKLS0tIGtLZllxalJZSHQyalZtdWRmTjhz
            ZWdnMUxJbUVJSC9DQ1dobThVVUhTUmMK2zIgfIoTcuAAEbeQ7GULnmBn5xC0ApBo
            QhblHyaokUBOrjQNRityATAcfAMeBvkUT2tKLJLYOttZX0aQiuVBFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T14:50:12Z"
    mac: ENC[AES256_GCM,data:afIdZa12DuwSGsWF0sE7MMY7gBguS6NWP1M8O6cp4yn4jFUfuS39OX0o8SPbDs6uhjqZRZ6/HvMhGsnboU6k0Xd9SpDudVMaaNgtpRMlFix7Xjsqj5NZK6hvl435xtFZ3GAlTQO//WfZaoFFPot5XGQDjYTSwYXVppj89+PL1BQ=,iv:wiutL0KkJRHXzIkoq95vPhYjIBjCEfl4ry4bE1XTai0=,tag:YqGs334gZeneGdb/Egz4IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
