---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.0.100-192.168.0.120
  METALLB_K8S_GATEWAY_ADDR: 192.168.0.100
  METALLB_TRAEFIK_ADDR: 192.168.0.120
  #
  NETWORK_K8S_CLUSTER_CIDR: "10.42.0.0/16"
  NETWORK_K8S_SERVICE_CIDR: "10.43.0.0/16"
