# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dtuRa/3Orm7QRoIyuyLq,iv:oslthQrVJJMhCVy4z2fCF5glMTvL/aR/+IUGhIQ/WuI=,tag:cz1zUh245soV35x1hUl7aQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PthfCkOWsHGnvzoyZVbS8ZU/DSHaCw==,iv:/jrg+w9+T8TxThVTDLmk8hEC9nJjp63FugXbdYxs7BY=,tag:Cijih/WYQh8JuYnx+lC8MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcTk3QUJCZU04dGZuNitO
            dVdURkhqVnUzWFBqdXc3OGVUSnY4aUx6TmlJCmZQNklCUXF2OWs2NzdHTkxpK2hq
            VU9vNm84MXFPVmRRZThkR3VZcGc1WFkKLS0tIG5oL3g0R2didkZvQ2pxNy95dDhz
            cVFURHVLVHBuS1NWcDQ2dmxsc0VXYkEKE1QioDjWqJgTD1em5Ia8w14lEJXiBVPB
            QgqpC/xUHIdIs2TeVd2tuv2AGzW5/pB5qtcRc0hdKU432GMcGlyZcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T20:10:37Z"
    mac: ENC[AES256_GCM,data:udqVHUlIv8iUx4z861dqWuZRcQKeJOvoaZqn5nKJ+7jfKYm5HzHiWEOhTyGbb7t033SkmLq57FcI7JJUdnkhhxl1pnrKMSz7V4oPNgdp1PXZAyfVxEt9fjtY5TFm89Gzl8do8x0aIwRRKD08cTSrp1VU+zNhBO8ZrAflSjdU3S4=,iv:Vy/6RRsli4Xc+A744Z5XGMJXbAgi5ro5iv8fuhJTEjk=,tag:9C6a4aA6+2RCky+T9barXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
