# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgresql-secrets
    namespace: databases
stringData:
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:W0LCRG1A5hVaCbTyh1Ssi7q+eQ==,iv:I5XXyP5psvbAVFcd8yk32tUaaXHs6A/UpFuT80lPeCM=,tag:/fdQJMA+2bLYjqdgohuOgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dmRwM2NLSlVMSnRUV2h1
            MGJNbHg2V0h5VjFUMjVaajdWcUp1cnhEUWlRCkxrYVE4Q2pNT05nTlRTNW5FUVc5
            UE9hWkZxb1V6N1BaelQrY2szVjc2NkkKLS0tIHl1amNSZ29LYUVCRVZWYWF0eXRT
            bCt0T1hKYkxoVkpKaGxMajdNOE1UWkkK/Qnhs5aG/YvA5eZUPkY3snHOB/okzHqs
            UMdhH5DuGTFtYYv94wlsLamIv+9rTUiAmUZLXNhCUAPFGMnEUQg0rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T10:44:02Z"
    mac: ENC[AES256_GCM,data:zMM7oA4beJY3YOg1ejNBwrXAKWgkuO45aUEU5jOpp6zquUjhWdm7luQB5JFtpkd0B0I6PjX9diodosvqg7qXyAN/B6U9zh145GYvmy55BQgLw8sWWfzKFex7RkgsLeaCy1trWa556G/0vt4UIWKYCdFo3gNWvFMdSsOJBrleY0w=,iv:ChirNgwO40Ex/1rVFXC+vJ2Ar+wp8bybypb2TlgvcxM=,tag:i+5Wiz8+pNNrq1DJqgJbMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
