---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-vpn-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-truenas-nfs
