# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: networking
type: Opaque
data:
    cookie-secret: ENC[AES256_GCM,data:Sz57yDoZcz7LS/X8gY0XIJs0KWyYASlpUaArfQ==,iv:cbX1cS4UoGW4v/GixQppEIeFoeUoNiWfVqbkcno7pu0=,tag:L2cbjqJuJRs6100ksXIcEw==,type:str]
    client-secret: ENC[AES256_GCM,data:qSZoeaDkbvwDr38HAQTAsbiFQf+bt1CG+LkkL6oy/lzgFz2s+Oko+OdFJtThQjf8j3ECAxpZMZs=,iv:we9X6ihfoMY4WbBVJqyJc9jwPKh1HMXVHpIUERg4jEw=,tag:YIO3foKK94Jc3S7G3S6YtQ==,type:str]
    client-id: ENC[AES256_GCM,data:MqTLvj7dLfHQMlpjL463TfkvXi1scb41wl1qPz1eKNqM+9fESIAoo7r8SPk=,iv:q4Glf2hbJe7dPTZ4Wi2M0/y3JscRfRazF3aFU9M3Nn0=,tag:z7Zp+PjUoGF2iC6pjID6ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMC9rcEdLZHlPNFJOZTFu
            N2lldG5IS2pHU01oRUt2QlpQUGZTRlJTUUQ4ClBvWEtGa1ZSRkxXSWZYRExJOWNh
            YnpueVVzMUZucUhYbXhqcTArYlVhTVEKLS0tIDFsMmNGdkNoVFJTSnFsb0MvaFQy
            bnBGVEpZRHpPdW1tbTdrdWduOWdYUHcKpGU40Z3NObR0Ne/9eUrv4SqgQrsJZcIx
            A989iEs0UHtF3P1zee3M/H/HvJ7DG3L9M8Hnw/Alw2kcTghsEAC4mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T17:47:52Z"
    mac: ENC[AES256_GCM,data:xLvwJckDNuMUAP8nGywtZcvAyHk/8htxtOwsIu7NVdtP7TRRHbRNFdgjoGhtlk0yhM1gky/61EIxwO3/XfExJd45/qOIN+uiC4gBaDhZWvxLobYM2s1XydtTVhpytJzRaw7pWHyIy94SYomveOjM9QG3xHHN9YdG3xtNaLiblv4=,iv:LGS6K7ifxqXurUtBdwTMykGzmiv7+IBeYGBoFzG7JqQ=,tag:eIXPCXEKlKTRAkMd0Tl/Xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
