---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Standard Resources
  - ./add-ons/monitoring
  - ./add-ons/notifications
  - ./add-ons/webhooks
