apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:vIRHsVI=,iv:cptcSlc63/mFRLHlrNY2MzJ5yThlJxZUhE5WybcBEo4=,tag:tPPmz8IxnlQwLK7I06jKlg==,type:str]
    password: ENC[AES256_GCM,data:OYlt+R5ReEBrkImOWrapHyaY6JgAKcT8c47dLQeNsiPJCjcV1QovvjpF3Zo6oDNLIIfrcXviBwYLdcGl,iv:NuPvI54EGGzi7KpSxdlZI/Zo3rb5VLfua5VKpnMPKl4=,tag:pGBUt8FiQrnl83YIBBLmrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVEgwa0w0M3RJZ1liUHZt
            NENwbmtVUmtxUXFpWjRpcGJVeVJoVkdFcFdBCk12YitLWnVhZ09sYWkybnRSMGU2
            UW1LUS9JVGZKbml4RU1ZaUdSMEhOeU0KLS0tIGxXTXJQSjdzMjljdHV2b2NPbCtO
            enF6Wi9WYUlyS0tzaXdRb0pxYXJUeFUK0jz/EDL7QEvamYDRm642a6QBVq/CiCb2
            478gkL3GP4LciaXG3oD9wUV6XkiqfGAzUyDdJyGq1D4EjMgA8QP8bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T11:23:17Z"
    mac: ENC[AES256_GCM,data:Q6TNOkQVtmO4dI0Rpkjdn4+lddP/sXyU0JCXyUCN7E8rS5mAj6ecGuVY2iLNAncfNdITHgc84go2qSRysaVUXOibCK7wQAJ6XjqZTI0qVmyKE/nMOkj+Cn20f44+L8n2olmZWb9v+7YDnp2a2cE3RTYnpL3G7u0m6bgAdybF8pw=,iv:xJ7YOXMuudaL9e+mLWy5/VPeSvr7GbMdTdWlQo3vMF0=,tag:hyQBD2XHPDcxCNmC708gSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
