apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:zyGCQBY/dxvrWI3SqptCeA8KfW2kBojgThJKg3Hu4NeCV41ngcXX5NJqDUjEjzK7UsNZJhi3VGLdz4AG,iv:4jVhzTRUw0vecO7SLtQCiuZF5MlrAnvV8kgXdC1KkRg=,tag:xSaKF41lM9rLcCq/mKWctA==,type:str]
    username: ENC[AES256_GCM,data:lMy5mgg=,iv:NlRgC9dhlnoe/TomLYBhE2vOQT+9omB2xhqpjjdgkV8=,tag:IdkaIFQ0+gNnJuCN8y0UQw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU2NCQXNNWEVCd1F5TEND
            QXprV1BoQy90UWFVeG5OckJZTFI0ajlKWEg0CkFOS3cxVU92Um9TZVozTjVMcEJs
            NHhsdlZKSEFETm4yUW51VDdWS3A2KzgKLS0tIHN6VWlybUFHdjdCa3d2NnlDN3Fu
            cG1xYUU3RE1xcnNTRWsxL1hWdEp3SWsKNcCIRoTkQe7394bZaJSLXnqlDytrl4QH
            9OpYvu3TV9ZLWA3Yx5sSak/S9jRPWAGOLEU2k2cF3VKRPfbts7yKwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T14:24:22Z"
    mac: ENC[AES256_GCM,data:Qg/Bjnk5LPb2HzaXb9WvMMtmKRerRrE2Jvcrh5M1ljqggqN/BLg4kjKVkpuiIsIqENyr51TXCkvdbf9uwLULtU5XzBATCi1jlUveJzLrdySHfJqJiVyOij52yI1lPaZ+i1RqXdumGF7W40CMh7p3OflVGU2KC7Irw3fDWO9vb4A=,iv:ZvlpqrWloQqEFpwqraX/eYAutm/UiQI/qd9EBF3vG5E=,tag:GyCjXudKyLSxcSiOgHDYQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
