apiVersion: v1
kind: Secret
metadata:
    name: mysql-secrets
    namespace: databases
stringData:
    mysql-root-password: ENC[AES256_GCM,data:syyticd5JlABs3Mq5BXT0Y6l/g==,iv:N8FLe8GgPKgcoPFHzqNJMxXzL4ynyTCRESIAGrVDrug=,tag:7jf046dHpggC4qa1toQQpA==,type:str]
    mysql-replication-password: ENC[AES256_GCM,data:WASNR5YbwUa+efAxlrk2fxnFZQ==,iv:aElHL7PnpR8IAu0f5VZ0enfDJ5X9f+nt4E6wo+0/OQo=,tag:EAyC4jv64Eoxp3ANyZuugg==,type:str]
    mysql-password: ENC[AES256_GCM,data:B7pP18oLDFs62+eoUbS2xyRHnQ==,iv:eQE9MS4RnPbD7JtnJ3BAh7xCbzJTUauN/jG+i+FpcmA=,tag:+FDmzQv5IyZI2hR7Qzksow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ3o1RW03V25oRWdZVEdG
            bEpjMmRRSTBzbFhvTm9VVVpaWk9NcHZEVjBzCjNWTVJUT1dEYkdjdFpHN0ZPUm5X
            RDc0b1pjd201TkhOY0dpdlpwK2tNOTgKLS0tIDh4aVh0RG50NTVucmR6bVNkVzlC
            d3BiR25KVDJOek00QTQ3TmsvaW1lSjgK46oi7a8oSWCG4bE+UYoSLBzGC9/afuMu
            C4DYa77I7zIR7a8qIsaXbYIshZ8qkA2bRW8YmdPetbe7vDsFZ8zvQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T12:10:35Z"
    mac: ENC[AES256_GCM,data:lVSYqYwv4fz+Ps2ytMpm1uhaJ/NE5vriTceqn9vJKgVtB3Raa0idDsPlYKqn5vE7fJyJxClTdsl3htBhlJ+YrwOq9y1jbRuAcf3qGZVAZ/BEKvcTLHcEipBX1RADgt/x7VypxsuNC9XJoj2fmlcfCRG8fCXPXNN+BYunn6bwMNw=,iv:o4ilg2s7Leto9xRYjr19NkXQNOXdX5Mfq/hnHxZlaNM=,tag:Lpw+c8xZgHP1ZNraFhCBGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
