---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: downloads-gateway
      namespace: vpn
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5@sha256:132afc4672c3db673dfd9c471ec41a95c85a1266eee638f7803f86cd6b21700c
    env:
      TZ: "Europe/Stockholm"

    hostname: qbittorrent

    podAnnotations:
      setGateway: "true"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - "qbittorrent.${SECRET_DOMAIN}"

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        type: nfs
        server: "192.168.0.12"
        path: /mnt/hdd/k3s/nfs/media
        mountPath: /downloads
        readonly: false
