---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./default
  # - ./downloads
  - ./kube-system
  # - ./media
  - ./monitoring
  - ./flux-system
  # - ./vpn
  # - ./system-upgrade
