---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - default
  - downloads
  - flux-system
  - kube-system
  # - media
  - monitoring
  - networking
  # - system-upgrade
  - vpn
  - metallb-system
