apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:b5GFEzV1UuT379HR,iv:VD4joTNWKhABCvDaR2//lzTls5kGsMMKJMTMk5XmcHU=,tag:P77MdXa8glercIxwzkqDMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb1IwQ01QRjdDT1g1QnN3
            MXJsRE90RXBDZSt6MnpySTd5RnJFM0dOaFQ0ClFhZGRiUlQrbkt0Q1NwaWlyUUpk
            ODM3VnN4aTZ0d2ZFOFg5UXl1YTEzbkkKLS0tICswWDRFU2VlT3Z0clhBMkMrVEJP
            SmpDTUVLT3hMTk02VEZFN01ER3FrYWcKZLFDn9tV+zKRT+ArrDg1W+XQq6Zo+5ky
            PelOJymulO5aeFKne6AEvu3S1xcgxEZoUdVA4oVI7nPqzZNdmpK+pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T20:06:47Z"
    mac: ENC[AES256_GCM,data:HtZv/le1bcJPHlLVHSBy7TgQB41up1w6Ttrj4pvjmK/swOqORtNoUUBLIXm0lK5bmlmVdZtornKti0mMpALySSo3irpN2iTblbGw65i4AM4Owg2TdRKV6LSSraAMP/pZZj307FjrcsGcMwu5mZAMOdxsVfAMYtyPgwKjkTvDtUI=,iv:op9kWKV5TeTHwwdFs5webTSL2gHCgiirjl2X3imuDJY=,tag:OBZKWJXg4K3/n1g4dqcqTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
