---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  KUBE_VIP_ADDR: "192.168.1.210"
  METALLB_LB_RANGE: "192.168.1.130-192.168.1.150"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.130"
  METALLB_INGRESS_ADDR: "192.168.1.150"
  SVC_QBITTORRENT_ADDR: "192.168.1.131"
  SVC_POSTGRES_ADDR: "192.168.1.132"
