apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VmDfQeIpp2p7U/m6RM26,iv:mpXOCwj4fJFdFUB9mRHYSI4kcrkmHGQpELIVT9RojlA=,tag:C1FHA2UxwYgNAyPSyMtg1w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:nbgjWce4WE29Z+fhGeSFeIatbHZGuA==,iv:CNogmFOiSq3C1uK+yv1BiP6qYN11TGlVv/H1gstAq1w=,tag:lU0sSvUTNZTyDl9NXEQ2NQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:uTaaG+eek4PnzbfosBxR89WSIO9oc7pVXHcTUW0j9Y6QD4Ce,iv:XsCcYK9N8/Bw4EchD0oHKsxQEtsmJ7cztbkZjaCfy4Y=,tag:BJawbPsGrvRE7pinxUfEDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbld4blZjYXRHTDlNLzc0
            d3grREJwMlVkaklJV2dqSGFDNmdVckxwa1JjCmtaNGhXUDdUTDVXY29Jamd6QXdj
            Q1IveHFlTXB4eGtCeFE3M3ZJKzNvVVUKLS0tIGJaL0ZXMGdQTXZhdmNaTjdOeHVw
            ZFJpZ01nSExhYndzS0tmWENyckhRaU0KkTCz5q3Jd27DA/xUHE1vE0yMaB8nBCMx
            N2jvnjztzaYYbdz6cq76pnrMBHiQxH2vVGxmd01g3jLyZMQnlDbw+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T14:14:30Z"
    mac: ENC[AES256_GCM,data:9y2+g9YbxJc7/TtDnI7JSJciYZCulKtW/Raqf8bU9yKZU2NleLXu4X1LK/XLsCtbG4uPdmPAamEFsFAJe+3i8sBQ+Jis8sqMUrk9RZ437YoFammKHIFB2LdqdlZk9iUOq2RR96RO+Cg8ujG0B/aZUI+5eo3hFtpqznw60wk8AmI=,iv:LfDGk2bf13O6K2fmJekYrCkCZtzPavB5R5Jt2QHxNT8=,tag:HDIty5GPoaZjgRWkhqZaKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
