---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  KUBE_VIP_ADDR: "192.168.0.210"
  METALLB_LB_RANGE: "192.168.0.100-192.168.0.120"
  METALLB_K8S_GATEWAY_ADDR: "192.168.0.100"
  METALLB_INGRESS_ADDR: "192.168.0.120"
  SVC_QBITTORRENT_ADDR: "192.168.0.101"
  SVC_POSTGRES_ADDR: "192.168.0.102"
