apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:dDBW1jHbCDGfrEIs/8obMfZpXySED0rF4mbXt5rNeheVIRCI,iv:uw2wRRp/xNtZPlP+F9axyxyXPy4LUP8jLpYsLPL873M=,tag:fyV7/5M5FiJXtm31k+0NGw==,type:str]
    credentials.json: ENC[AES256_GCM,data:JutSTZRjvcY22ALv8gDo/6F7wBuDOojX1Obx7573AbjJK5n0PrmUPVwPcK4qC7ih7ehz89yXBxkNoWY8FO2U/pRfILg67nN0OjLroQB2bWbS1ZmNYRLcKkMhyVH4f/ne0i/gX6N6FozbLTno8nDNfr/LnJ+0EOpwCbA6VeGXSvPCCddld0W85VcqsWLiairZHqb8czhss1Y6gJmPvainvjmmoTpo79/kA/ty1Eggkg==,iv:fUQHvVMgj8Ziekfvyo2+ri1m7vsYqrWQSDGiBPB3p4U=,tag:hPjTJo8tTWLX1zoMC9+KJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMjl5cTdHaTIzRElULzVE
            bE1DQzZwVkd5WE9rZHZPdGtJN2tQZnRkWDFjClMrQVk0d20rLzlFdFhFdEN3dmtN
            MmJkZlBQT2FacnhseVFXa2ozTGliL3MKLS0tIGQyQitCdGdwYVFORVRVaTgzM2k5
            VGJuN2VXSkFoeXJvSnNLQXExZ2VKaTAKwf63+OWZ4YKFHPtJ0NtuJ3kZxYce+5cs
            6HBmNn87aziAztEStRM5neYDwZ/gAG93dc8NcuZpTScxGGKkWemfbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T11:23:16Z"
    mac: ENC[AES256_GCM,data:C5cvc0NahX0ZfVTmh5lOqLXpeDfMa9ILqe8DNWEmUOydho3+plg+IWTl13DsxaABMeJku+UgaXpEnqoQrpMFRTNX/OB1yJ8jPeiZu+JnjMWs2j493YMKGndTW/dP7ty4NXF9NZ9o3wITLjnQ49abVRFXUBNEvGy9TMMiVXvdg9s=,iv:oCf6ZwXhD33psHG49NjFYe1oJVpfaL3FSfAn0qFWSow=,tag:q+qDXIL+fhhz3INGg8+IGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
