apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LIptC5h9XZ8uCYCwjdgFNhbjw4d6EOHjkPPK+VyR9B5YJNWU,iv:t4aTivRCoiFF7SNGdGqmWWOtHeTjoPKUafu3mgzOro0=,tag:PKkViYDso2zknPzlkP41Nw==,type:str]
    credentials.json: ENC[AES256_GCM,data:X/c/XzqMQ0EQgeO522EyhaGFWxK8Y1T5XIszrK3aQnOI984VorSrXn2zzO9qIdmiwYSO59g+j3YohsJSulJaYBRoHkv0EnT7D4WIFZ59zYeYPrre3ms9CB0wdMuwkW+oyFDSXJiBXQ3jq+PyXHro+fWyPphQwGvMLf4Zs0gSjMvyk53I62uOTfvITk0KspEliRyeRxYbbXMv05WTHycrDB2aps+HNPGMOF43h6Niaw==,iv:xqV32pFKXujqN/HGleiZXw9PcMSAMkOLeD9pfaQb6c0=,tag:SxS2RwWNbJ0k5pxN7wR5Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZTBzTWp4RDNRT2dxSFNH
            TmFvY1ErL1QwcGV6TEtNMVhWOFFyU1plM2hzCnBqRTFCQVgzNUh6N2ZLZlp0d1p6
            Y2JyTDBWQnF1MURBcFYxdkI2dTV1RjAKLS0tIFRtSUVvYU5zMW9XVmpWNmttYnVH
            SXRGcUJ4SUVONksxTnNWOWRwQUVOdTQKkg+oze6d5eWd8gYfnbUlxOZvy2y6+7Ge
            T3rpV5yidM/XEPBN9TajJdy7+cHwS2tfSDIs5xuyuBjZrTmYcrBbng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T17:36:28Z"
    mac: ENC[AES256_GCM,data:FNv8vZrxhrQSUIJ3GEg9Huc3/8rlLNNtjPIzTVAN/qDDItcAEnQ6OWyrXLxHNjavxqbFd9jtA1UONtNimlUY1pPC2piaN1HqXgTG9F25aBM3R+QJ+SL+J3vMH3R6/5z0/cX34xCl710nxqWSaCqybzKqX9qd6dUSB6xlEaX5vTo=,iv:P10EygRAAm/Cd0FLC/jSgqh34ca3fKsJLwpehj4wWE4=,tag:HoJKEt1EeAGgX+IRUShQkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
