apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rp/M0ubBnqpWnsQe8g2MdOA6Nh78dIxQ+m4orAtgtWLAEymu,iv:99V1R2fuEiAE06CnlbYbS+X5u5PtQzUafaJ6Bp5c10E=,tag:kxe3DTmEfU6kuMAdpFd9pQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:1UHzXegSAfIFJRI+ox3jC5okK+Tp0G3xAzwVuqerBAtknrJMlM2d2H/gsmPmHxdR2pH7oxeMNLpmMKl00jy/PUDkryyEF4Ne3WbRccp75onijQD8S8Llu1eBjOTGI7C7OEW9jEErQxBDWGwnuBlcYZzny/8I8FDHcfN9wnxBD35yAaoFbztupAHk45tD0asoq3WmIlOGUNXmJgURCUFZXpwza7Z6E708QNsZCZ13EA==,iv:kUdPZKO+yXgaWHHbHuxNyx0Lt5xPkGUzUVVSKdIA0P4=,tag:3EH8p46aWxASYJs0IUiC2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSnE1VWNPSjJSZ3g3cXor
            QnJ3Sk5aUnRpOGlhMDJnSFg4S2hYUjJVRmtBCk1nekx4SzZWdU9wdFhBYnFpbWJE
            T2RCd2V4MDBzVDJObzF3VlRVWG14MlEKLS0tIGpLbkpqdHVBaUE3STBDWVVOWEEw
            MlV1N29pY0MwanVTQWpEVjJPOTd4eG8Ktb7OGxrCQURAXHzC/vEUVY6xZ2oERCh5
            dZO//IPu0q/XxrgMbS7300VNzxhXYF5thtH6tcmoilma0WuJyd1IuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T16:47:48Z"
    mac: ENC[AES256_GCM,data:VwyIgZBldBPJsm+UU4JyEtTRPQNkBnw341ua35tm6VuVRGT05D0rOQYE83iI+DRx3TJ5m2uoiasaTVppKxroJTrhvnO6g5YWlvO2hVj/OP51HJlNuCvBxLKwz6c2dLqLR6z6hKsFpaTtgcro5PW1Xuuqf7+84O22nnzX00Ygp3A=,iv:8d9OdwOjvDxqTYDD1kHw1KqhTGZJVpjpYTIAL7UB4Os=,tag:LrkeeT4bRSPEMjkrmZ6G8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
