apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:nqnN8dG7ZiMubD/9IRMp+tiRgoIqim4Y,iv:cCtW0MLYW2AQfyu1l6zNLENnkPnP7+A10jgkFPvh6KU=,tag:m7PtINOBS9Ec8wTrDcHPTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTUplbmNWanQvSTVNV1JD
            cU1mWnFIMkZHU0xjOHhpM215OHZFWndLTVg0CmRtU3hGbUtMK0xSSHZMa0xUb0s1
            SmRLTkFCZUVWdFF3ME1oTUhIM1BkaTQKLS0tIC94RFRPUW1qRnBXcmFVd3ROYS9t
            cFpmeldHRENPNm0rMW5Jclo1a21zL3cKPjgyQYZ0qR2nWpnpR2qQTUnwSOkY5fsp
            SidU0Fm++VxwVry/arMTCLi8XIETf4SiObiDniHuAVanIA7v8ZLASQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T19:25:08Z"
    mac: ENC[AES256_GCM,data:cxCUQHufJ6vrpRcHWbUIaV6YK+lR+q68dDKBlTVzIk2vp3Cf/01Omm8FdK7nNLU5NLJ68gF9ULvsonbPz7xqdVdgGQeZ10nczuHrywo7+cyydzrKJ0WzwMR6lhUWLP4L7WMJqTqhRTVF6XqAHE3RaDgIfSbTjX0gN7us274GKjg=,iv:jLG6dvsSvdeBYn/mzpouEQMIybRUiS60GZBXhrkDE/A=,tag:FkZsjgMmqGprwP7WlsVylw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
