apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:ehp8opVFGd3YGyHLcpAIEW4LheTgG2BYzbdgonPCvf4=,iv:hS9kRgriodO4JGxY83Dp4AVEumpa00d97ggRbaJeyg0=,tag:vgfEUcw6Q4eO76o7bn8mWg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:gDpIkxQBTObQjwo7gJbmx13IFG380/x9WrO3vKoLuI8OzMBJ,iv:A1ZGgxO34+o0YTKtMJ5qQQ/a1LviuRN9QBVVt/WjCuo=,tag:laT+kn/oaN1TG4VXyATLhQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:JN80CRekukIxGm9gnxWUyYnw5z+JRgtbJhpJTKI18DOToVrd83/1oQ==,iv:oXmt8DZABRIg8YmTn3oTEGUTZOd3TRGngxdE0odkefQ=,tag:WaFD0Ykpmo7EBGlbWRmdXQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:BEiij0g=,iv:6Ef1onkAb2hxIyPSDlS0AlIzssu+ZF852SfgsiWKUCE=,tag:0nAhSp22NC4JIqyil6A63w==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRmNkYWxYRU80TEVmcWg4
            QW5saE05TWdod3RvTGs5TEZzWktWMktyNFJRCjNXcmlzQjVWVUtNeUE4a0wyd1or
            RVoxM29zcTVDSFB5RFUzTm01U0Q3TE0KLS0tIDVmUlhBSGJweThxSnJLRjN4dkhI
            ZGxVTkJ6eTBXNGxWUnQ1L0w1TGdoYUUKbMUtaREhX8+rGSFpgDhjBYSv8MK0rTLO
            agisyDEWwl8tVMbRLSq8CD2inPAZieBumMsEjLq92GICQC4OZNpPuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T09:58:17Z"
    mac: ENC[AES256_GCM,data:YZk9c2ug6zgShyR3m0ma4M4xgr/59fUIfV6gISMfjkcB/7Qcg5x7uJtYloH5EZXMG2UNAiFUpMrDqiow8Q6zICXqxCOOyDV+l2acHZSK9+LRWnep/qc5O+aFpxvi9OeTBkxxhgeV9gimBhdPYPrbdvNVGhUgN8814CPR03qRo94=,iv:Vw8lOwYnH7NlZEQfU0lO4Sqh+HBOj5ite7Q5mT+7iWg=,tag:KzSHVaR0vmmfPwH8s5+Q8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
