# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PsLyfKS/WGe7fYIlhmGObcWGlw6fRwxNzzxDtbtmkslKDYBHn4b92A==,iv:MOApEYLeVyqiuDYbG3Wk5X62e6Rw5Ff+R74QADTVq/M=,tag:TZ00KGfe0TYunT9u6pqycg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NjhsNUdXMUc0cFR5UzAx
            SEoxamNOUVFFNytUTWlHeHNRMU9OOU5LNTFJCjB3b1ZUWWRvRkhTdVp6b1ZqRk0z
            clU5UytTNnliMmQyL0laQzI4bGtpVmMKLS0tIDZ0bGZjc0N6R2YwQ1JmMCsvQ3BB
            OVYyNS9xRGNEOGMxVlpIVFBsT3NQaDgKJmdeaf5zsByCboXnOBrqSMoBrRyXPvhX
            7U2dj01XfhLCsOQwTqv3GV+MlG8w7qdQAMFNX+XB9P1pRIeFhRf4CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T19:14:36Z"
    mac: ENC[AES256_GCM,data:xvD0vBpHdyjRkbtTvmb08vTKLHCpnMaGELyQgDHZMadRz2yPbTlHUPUsPaCEwAPck5LxmB3fLoaqibfE1ZUHdXuGL8F8nzAqgfuMZoDn5bGRQHSdqIO+W0+D9AyWlezVgxjFQpm53oVFo4VojStx75kJqXX8/wUrfcHBDY+w7nE=,iv:y06E2kyuEx+lh82mCr1zBtmwFJuAhGJElZRpIXCVdB0=,tag:tP1F0miN+volKI6wZKeRQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
