# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AVlIRBtOfNQzVvlet0j3jn8KAhFVeY63izy2xOuqCyr6fi2iLOaveg==,iv:Qvvrwoyd2OP9ge6ots63rwaCAYcpEWC/Dp9Blt5SAoo=,tag:SGCtSmsG/ZZ2r0j2yCHF4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxajJCOVpHZmVnUFVIK0RJ
            YkI3SC9BcEE0cEYyYzJLUGxjMkt3a2lxQ200CkRqSHdwZEpDVExkNERTTnJ0eGky
            a2Y1NzBHWkxnNjE3cE1TOVlmcEZCZEEKLS0tIC9lVFRXTnp4V1BaQUVZK09vSGd6
            NjVoSXRFdUF3NVpmVmJhTng2cW9NYWcK1O5B7YQnlAhLzr6kadpa2F28NKXXb8aI
            09+6DjwXn7ilpE52F5K1BVbWnqmVsh8udUz3L1lK1NF7ERA8hO64Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-17T19:30:57Z"
    mac: ENC[AES256_GCM,data:dxqKcOyy8O1seVO+GbEFjf5420Tb5Ub1g0fZ3Qo+QnAaIHGABXie/+UPPeYoJDSJQiHxNILrILeGuqtfLeZhKfYzJhn65GAvJqzMMMpWwnLlGRYGRNtVUjXKKCicSS4nmm13232PmG3CnsJjJzHGuSpt1ONNi9pG4mcDmRR+X8Q=,iv:gmsveOf7udqxlXibtfXOpqPRKT4qOPKo5cpvZwHOHoE=,tag:xG2m4FOjCUh011V9TKwteQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
