apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: nfs-democratic-csi
        meta.helm.sh/release-namespace: democratic-csi
    name: secret-democratic-csi-driver-config-nfs
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:Rc+PCANKBRClV8TAzXc5oSlxljo4l/z1hSAgG15YDp2FPK36mo+EAupLDDJD4ybxQ8G3gkjZ75Qj8Fs4+6HYA+WJjWbXPhh50GZziVLfdnyX/0Zo98XVNbRk/YlvKSqky9yKHYOvKm1As6kPTD6RYnIMFaBc1IdW/nrCAk+yNaJj+kUqRwPm3PVoeakQM8TOr7EDgHB841+4onGml+pQfCpnk3GjgVzOBrB4omejd0wAtj9OHTsH2wbQInoMGroLmri+FaJHj5Tw6ZEzMs7ImtmTQ6mPco3iLTI+XXJu9bGyVi6Kf8qjAwDT3BZOp8VdOZh+tSeMrY53V6K9mPssEvtvRZG+MiiKznyXA/SQtyje9v6x7nUC0LdIuiGf08sQf+3hvV4O2zt+mPfKUtjmka8uC6Z8kLvIZ7xwkdYUxnuSA78kDvO4Fowph22uVAb4yX/6xWs8CgOQNXS0a5MkLkzVKS4u+eRlpwx7Ru73ViB5JtJ3ek4jkcMHeI3EUvWoh74KmwRO0sE4WcnZApDH+tWsjsnuufpA/KbmMYNLgey6CKigKkZgVQlMV8SDo+KIRWDmHZkf3bY6glR6hgMq2cHBG/G1u/3Pi4ClSUCVhk17j7Wj0sUv8dvvRKnNywmLeng8HrfQ7EPhkBatcfWN6X4FNy8lPCNlxoHOv3CUKXuIBiEyNNA4dIug0OF9WZ1OcKfuHl8peC4ThWeoVCTj8xqwFhLY3INjCTgvDXJMSTzriL5YZu7IKhtpV1Lfvc5NJVJh+gbPG7Haj/xKuuTRhMYms4IoTvDWYUMFb86cgKoo9jU5lt6h2SAdSUfAoc/BFOXd3u4m65nUq2jC0lL5QfLGzFx6Kk4j/VYUR1a9189is8rJtpvw3rwljXtNeho1OqijscryEvrcsXjP+XrdtaFYLV1Lp3s=,iv:nZaegCoLWUzhLS2Xsl0rSzQH801CGtIZFzJ1C1kw5cY=,tag:jgjiNOjlJA/y7e9WJsCQNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcEtpWGJ3Qk1PcWtjZ0o1
            NlBDN1hvakdkTklxMkZ4VWdFYlVORXFzYjBnCjFBcDJQWHNGOC9SWFdESmRoNnJy
            Ly9PRWJBMmE4dGRZSFNyT1JGZU9OeWcKLS0tIFNKcGFnaitwY24rQmcvRitWN21o
            WURKcHUwTTZGTHo5emVuT0F6RDc0dE0KcN3kGdxKvK+yOYdbMYD1tzWwupiC9hdH
            e25nF8tkuoHr7aH6YSQXhB3+tsSyX9Te0lI+98RqW6TOk0PzKimsxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T16:55:30Z"
    mac: ENC[AES256_GCM,data:En3YSDWk3AnxgEPu2mRq83l7BlNb+WsqNXUf6IjHhZ8Nboyf5QhFkniDitILnrmReWvoErunjMYrs/pQ0seuW7M3WPBGXgx15Jq8dRipJWFfeDA6CMakkzA1VvUDmr9CQBlyJlXYJ83l9TPwM5ZeZWcEH7+62qUTUY/5G0cbA48=,iv:mBbpiSP85p9SlYxBz0I5/eESmH0kFwVvLiphG57hZKY=,tag:9GD6wrIc9dzsMGkB3PYxbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
