apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: nfs-democratic-csi
        meta.helm.sh/release-namespace: democratic-csi
    name: secret-democratic-csi-driver-config-nfs
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:xFRhZMuzctsfHEkYWnBCVMv8UYgVpbPS0JG+fG6MvITv+6iWCStjPvDlEvye8NZTDvsMii9OH5/A7TXZMPRJo8Vzlr2G3U2B5eI1qF33CUFLnAnHkjKF5v1GGuqdjl43BqZ6UEMYjafMXjYT2PoORGWCFcNsD3HwzHPgZQNTp6ylAwfzl1b5tcFPA9KjH8fq3OgptWpnol87UbrWHbmIV7W1D4paYs3cF7dH8ErjmGNMMsaBP4v43BpbXsf95LCtIZCwGTQlKunPLGROnvRtV6BH4dLvEl5f67f+3sUGOntrct2+H6WffxmlWNiwHtQ4nVbHaO0K1RuoHmocqrMvPM+318St0u0LYx5TVrSZ3e27K7zYM2OPPrHiYCFZ/2SlD+ne+lVjXq9b7iQtgIG6FlAG9dKFVMA0dyc7QJHVwRlGih11HYAvuGJCCejRDokdn6kZy/jOKBzfO22NwOAu2g+LCmOakp/sBd9puQstq940LM2IIwnH1sjbZbeRPDKWYGfOjVdqvbTjXzl4yoaiKlPoUuojIDWLynatCW6BFSTlmwAweLYyH1eqfbRkM/CuvbHEPkpXM77lSU8oJMYD4SJycg7R9C5vHZ1bfQWRMIewx3bV8wUJt7PNEYI8OlRgkP6eEu1ONyGx4L8E0V6Z0ysVFw4AoVZrb88JT8Y3D109knH5Z7t98Z0Q4w5w9TZfqQKPlDjVuXjPbq2lKfB9H+vzNMd4qJe2gmHUjxGPLt6oc6jflNplf/HcB/Ej+VZY/VZZzpO7fmdYt8KSnFbVcNz6aDBiS/jGQodjORCplMmPkauwFaRPeywQHuWpOSU29jeBPFVHOwxRhZnstI4nqsiIYPSLN3bJlvt/c2pXcaF8j4tIt9q1FqFZDYPZN4vWSgvrPU+f+yZjYLhjBmb2EBmLcR67bBaeRyR4kGEo9W0YBxuV/5XD2wam2qgca6CEFSFFLTjWxNKwBHImaGUnrgpQBTU5+GLGZZKHsTMpSNmAU/r1+uI7GvXsHkbWpWCkQ6ocrPCSdYRypE2Q04mLNhT/YxgpzMnMObT120aDhJi+xJQBTbJpG7wB53rDRd6pgw9IL9pjBc7rIafkiQMtOUStEB0/r9Ksw1IRAzFYc5Z3ZJrZb0AO0oQQk+8je5+WtbEoVsHqDRa2ula1p9jqxxHT05L4xzmfBfu6qM0IjihjfI1BMrU4FIJ6HGfYKWcdnWe0SI8qTjTNWIfKXcxCs7vFGwOB2Y9wwfmCLvkPL53kvhMNgVna5740HpvXz3MgTKxTPHWt4Xg4o9pE+mFRVR3Ea8LeYk33JMNAIP3RWdVxNqLwI7suHkG/1WqsYwsQjkQGox7f+FVALeP/Ag2ZEpz4S9m+E5ISrN8MzhrOG7Jw/CqfnLGWehK2WzapoaxFXee0LixQCcsmHlwKR00pqZ9a3J2tHp+hjKx3HlpggsQZyMnjF5qzrq9IIWmiThwvuMavuH///dI92Ca1udr2qVSAdlgnOWTu4jiCYvr/QjA9oZAqMEP3Z7xPVfRRVTc/90FZpyCHmG/0inTbc3+cCMXVn5fL85bcYOuqtdtj5EIzzDS1rPZj4wLmsGE6drJRC29+M/6LQYR9mdcwetkeVdsO8tloPT3EQAXbwYPjq6wEtMH1rr0FZLEl+GULw4jiCc+1Fl5+3jCx05h5LCJ4LRUlRV+QPhmYHB9v1dklW/KAtYlq1GcdqtjaXiBlp5nnfV56omxBQWuxmGvIbS5SOpD2JNgjJ5oB9tqCkZfNBIuKAaBIh/PRNLq5FXvv185nLRC4RYbVbklXMCTAqaO10Y0REYy2cgtbL9H1jxAb2kBlhw8TknYImzSRejmqN1QR3Cox9oneYKas0ATQelSzeOSM2l4fTs82zAtSceDbtR4sb67NwKWWJdnDUUegiHWP4PtsaQoHq/ZoQQjDqOTLXskbLm+MSZ3sgrDpdaUvQmQytLe3ZsNTw87pbk32PjNyKvh4fzBrtCyaY14iyPCmiYgKPXBklJZ7CYJ7W27fje6heUhBiBpfQjpXLGrT+0UHmSn5tbwj5j5ByUXyNgYSauHS5QHHqrEQObU6YtCpIzIHKtwgWTTS/IhtxGMwnC5MiVLoo7ATh2wuBcZfvBOZJFSIEf/BVST8/D3w46pHV21vU2BH1PlSfwo/ReK/qkJbiUfHBu6BGxDWFaBEzGy/k853B4dXJA995KM6aZwj,iv:b1Go5juOKVnBbhk2nCcZG7uo+LKJS/ImKseMIigQhc0=,tag:WRCUifKmFpV3h3+Jsb4z6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcEtpWGJ3Qk1PcWtjZ0o1
            NlBDN1hvakdkTklxMkZ4VWdFYlVORXFzYjBnCjFBcDJQWHNGOC9SWFdESmRoNnJy
            Ly9PRWJBMmE4dGRZSFNyT1JGZU9OeWcKLS0tIFNKcGFnaitwY24rQmcvRitWN21o
            WURKcHUwTTZGTHo5emVuT0F6RDc0dE0KcN3kGdxKvK+yOYdbMYD1tzWwupiC9hdH
            e25nF8tkuoHr7aH6YSQXhB3+tsSyX9Te0lI+98RqW6TOk0PzKimsxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T16:26:24Z"
    mac: ENC[AES256_GCM,data:tw+Fae7rN8puAdqJoeNSul/PZgGpwDyMdQu7ttx+aEWi/3JryGuHu0UvVGHjhp3C68L4AXYW6lHa0BzCp5/81a+AWZZpzOHR2n4zTeMB7MWERy+EcEphZlUciJe9KwThPsbh/l6+DNCbfJuNGXYky6IaRB3LW/JQbR5+in4ekfA=,iv:knm5ETgAQcYOkubImG8FX1KU1dBxrJ+q7kt5UI8XzMM=,tag:TyEcPGbhUMFJNd39NCZvZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
