apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: nfs-democratic-csi
        meta.helm.sh/release-namespace: democratic-csi
    name: secret-democratic-csi-driver-config-nfs
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:Uclx4AikmYoRtDHpGFvYkizMSojmCYtNx2dyxNWxsfXpvln+76rKPaa0QL/QA9ZoDACFqrCkQrQnhBgbfftRC+hufJ8k0N+DAB3F+0ZicPNkKleNTqH4XcAq/bAJwUND2vUH+ZqMUmfhOHgUzJ37JbXtogGJh6FjsQEZeFZWS8dQFhPlb43OYSm0HnkwoK0YdsQq4m0F4AbsHnWqLKYoZxTdpjYdXjo2S4Nplqg2Yo64s/eN565FtplwvxK1S0AD6ov4C/E29Xu4g64Us1ziCE3LVc+sivwu+63cF9KuzRUH4yBQjXlGcPMLO5YrQbI8PHkhyGcSudqoBJyp5Dc2cqd89iUCh7RpzujvARknp0BygyjYb3S7XGAWZhGn7KeuiMqc53KQtQG+3yESVl9jy2yJ/IRnAAQg0yfjEDogA/XVxpKx6ripZYmoaePBjsmIkK+vUx91azpZYC0CdysbMPFxKfwxIRQ+WhKvpoO44CLANoTN4Z1ZSFnWUNfFK6phwhbsYUyPzcRx1hfyWx+gy8DLhEMffpbaknje5Vnttd4Ub8WOxx+UYKNy6Mgcb84JqOjKci52IkkOhza3VSroEGdUXHWYbnB9ecgrBNrcp2sJwn59rQBLstTc+K1SVFwrwUGdku447htTLOA+xG51b0OYtygy+9oU3+16+EH7uQmmB/fpoBteeU5DEsR2lyUTyphst8lcnaPEnV+DZLXVExX8tnu+94HnsbTafBpOC/6XidIsjelx3DbK4Ft/hS55TgXOam2TKpQtDOCRS6Rih1R3fgd7ULI/kbK8mouxw2LsDJ5gLaHN1FUJVPz3ti9kdhHAs9LJrE9D7l5IvDz5J1p494BjBxohTM2MH4tnNx7WK6UB1lbAe5YMdyTczOb0VNCjAXAlFYKyeLjziULaSoo1qBM1EhadwAF7CDkcedthu1jErDar4Q4VLtb9RSiUc2e1RFvP8E0s9DcOv2BYYW4+AUOHOijOVSnlm1ahcJN0/vTpVpiEazvAPC5bL9cs5IzcQEXoV5uHjq/EvNp3qVNsF4+3cb2/Tw+Lat5ZkfnNJR9/WLwe4X5jSIskQe8=,iv:4JCEL35ZPP27SxDbIKLUO0nTPZD+cTTc2f3v3rcYfVk=,tag:+dCNYg+sVvKwK4sHQMkJuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcEtpWGJ3Qk1PcWtjZ0o1
            NlBDN1hvakdkTklxMkZ4VWdFYlVORXFzYjBnCjFBcDJQWHNGOC9SWFdESmRoNnJy
            Ly9PRWJBMmE4dGRZSFNyT1JGZU9OeWcKLS0tIFNKcGFnaitwY24rQmcvRitWN21o
            WURKcHUwTTZGTHo5emVuT0F6RDc0dE0KcN3kGdxKvK+yOYdbMYD1tzWwupiC9hdH
            e25nF8tkuoHr7aH6YSQXhB3+tsSyX9Te0lI+98RqW6TOk0PzKimsxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T17:36:15Z"
    mac: ENC[AES256_GCM,data:Dtmpdfn/mCa54+7V46/xQZ1SWIxCxzQzXYoBxTbuwpGXEe8p3shJDg6qajBLmzWS8QxyHRI2iAxUCRgzQGNz/GMCcev6+IPYWPRIfWO5lDcCnRMFPSvPnqest3gJzWR/NuwD+B3O4YB4QwZ6/A0OrAMtzfE9O0AKpjs6XiN0ylA=,iv:rKuQnebMcFCnQC5jKVGInAYfVGAZ/MmUz0fSdw6BqdU=,tag:LUyIrVM6R8SFAfZCEpk9Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
