apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: nfs-democratic-csi
        meta.helm.sh/release-namespace: democratic-csi
    name: secret-democratic-csi-driver-config-nfs
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:xs0p+iFOZ4Cm7pBREMOBA+WNbrHlah2t96FG/kuMMdBOemrSFOSKRcLQ9OvUJTPCFrXNl2scamYaT+4JDVATDPfnhAwuzuFe9dz7E9AHf3LtzdLa4wy9aXiRmnJQh26G/c57bw9d95iMWWtMOLzRUiZZUvWs0RVvt+eUBq4j6xgYkTls6yzajbVN/JPQEm40inE+lT0dr3mRoqYfRXcF/rg+fUAGPupbec8mpWDiY7MgTWfh32T6JLmU5Rzp2TLV7hQvGZ1SZeom4tiVFcQXQZHMMDB4dCH+7uMKXlYD3cN2guB1QX50V6tSk34qv6l4N4OX764f1xSbvQiUDXv+/sElLqbNYb/Ap+ziEALZjyUJgm+yI35BOV8eAI05Y0czw0o6kSgKpGhDWDhUrKYpx1k01LKOzSQyZ3LOlyK0nc5UJubD6byV30pfMC6mKJhSeZRHMOnyXdilmh7ovM2wZI/vN40WqpvxM4E7B3VrCfYMkswgdIB+aMLNpUU75cyNU734hePei02iXSeKtkNxXrai/+Q8KUDd0elTrbPfdm2lt/AdbjQ7EyXUGJoG7H4fho7+BqiVQ0Rh1cLIBs6SNRa+ft8fVkfvmOVtAGJEVV0ADuH75nbvclPJdJKgD9GeQmeqDV104xej1iRPHbO36447f0VK/w3bPTY8IcMWW8F87J37fAgFOlierPDN9IEAokaECHJLfZr5mGWpGWWVmrsESbMciFsOBnx+WUU3Cq18smKBxcIP/dhRIla1zEj9EsOmxMFTCTU5bKvjmFaPvRFWiJd1ZWB1pudQkUM6jAoPZhSBipCH4nxfKJbDCl18htzd21aDjqAm+E7usakOclQk1F+7AzKaX68P0u9ESMm1hT4PYn14nYE9GvHcM+x173If26+DKcPE2RZXbDTNhUf3UlbOhxk4lw==,iv:P8vKTM+1HxYWw0qsJYOcxdLO0aoT24uaAHH5o04E57M=,tag:4NJZVOwbon01qbRp/01yWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcEtpWGJ3Qk1PcWtjZ0o1
            NlBDN1hvakdkTklxMkZ4VWdFYlVORXFzYjBnCjFBcDJQWHNGOC9SWFdESmRoNnJy
            Ly9PRWJBMmE4dGRZSFNyT1JGZU9OeWcKLS0tIFNKcGFnaitwY24rQmcvRitWN21o
            WURKcHUwTTZGTHo5emVuT0F6RDc0dE0KcN3kGdxKvK+yOYdbMYD1tzWwupiC9hdH
            e25nF8tkuoHr7aH6YSQXhB3+tsSyX9Te0lI+98RqW6TOk0PzKimsxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T17:06:31Z"
    mac: ENC[AES256_GCM,data:O/Kx5tHbEsuN0XCccp2+G8lIP/0HM1jHAl7MWGURBeIVH9G+rr7bGuD2ZyXYEKAyYh5UMpxlTBtF/UOSykvj/PVpewxhcTtPU/7n0ICBD5l03JQJLTTheeYB7u8fkZIjYF+muprzPp2IIEzXBEUAzoyIQeI6vS6UMuEQ8zGBBqY=,iv:BYu0qMgkHElPqLBxYmS0YhRAb2P8vDzZ+t7Pp/9BifE=,tag:bc278/XHB2rdZ09dj2v/Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
