apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
type: Opaque
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:xs/sjBWF2X1ihr42jkCvq0h4ClBPv5ZuqnSmUmGGRgKi5RoEDFtH7196m/q8BIXlZRNAQ77Mjf9mlWy/PoPC9BOL1/LejfcH0iHg11nrZ6nk6f8GrkvoZCy1umaVuuVyLmUAvZskhqSud4+9kznxSe8vVW9AEbR0yZyZP88tg+/eUjcK3eZpTFneum6qARqMdWvNbDB1v/upydjcdl7/hSlbGFTHAHZD+M+EA03RHwaw65yQkS9W8p0XZpVTQFYEGcK/IUnI84C6s6d6kZN7+L8SgRetNVeVMJGTbRXjQd8B95aydLpllwxrn+/iUS4lXkVoN4aOqmIz4vnrzLEg3mkvR0zaVvy//A==,iv:Qrr5BQsRvmNnSxwybwaunzuiR9fzrZuS6AzOl+ogWjs=,tag:pXugT4BfnSJHClxnDeFSEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd2JNWTR1bXVHYm5YVjE3
            YVgwMmtVMVlBQUgvNGNSeFRWN3p0RnQ5VVU4CnBVUXZYMXZqSzZpbXdGWXlGeUVU
            aHdKSThTWUlMTVQxOWFvelVKcFVLWlEKLS0tIGhxL01ZK2hjOER1VWEzaVEydm95
            K1dLcVprUmdXNHc3U0YxQTdTeVRBbm8KTZU27ouFnuJef2qgKcW85ouDPbxyyT2b
            DwzUmxsLrbwrD+g8TzJMdPKN4bJcWPHyA1kO9W3tHtfwrF3CwJgmtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T18:57:50Z"
    mac: ENC[AES256_GCM,data:0YZsq/enpWvvED636LiwtLtfcyKSIupviJTLcfZkXgWyUX3izmKBSxcS8ZfyyXx6SyL166Ed0YORPU9Uf5Z6bvhNnxwYUGF/ioaUywx3zPgBIVd53Z8JF4PuE5nFfyUZbfMG/Om8lNDYNd4mB/BSnBoPBZq/2EB3/5JjfUl+7eg=,iv:I/RxUQ7NvFX0aqRspzyhHBvuhXXYXG3OMUAdqKXrZhA=,tag:xr0VQNMMhdq8mm6WNixATg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
