apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
type: Opaque
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:efhWzWGSS2TYKR/O1ArDMbY5YMcXCyOGI65vkPPQOr5ugbLWlcqiXnatxnvOUI1OjLQv9TZD+JV5UFNu9UgRbPVoglTcP13f93R0RC8mu52XDDWMKSPqbFx7FzxQlcC3aBnjYLT1E6/bUYMR+8/RdokeQbdYbQ09Dw2okvCWLJv1ua0lYmb6HSRGpSydGeh8KD/wVTdg5Qh98xmyCpN6p+54y5Nt0LBE0F8isnU8VFQu3R3DtI2DdQNtTEMpK8aZekafdGtxPYieNOvrEKffE4QfF3RJh7sD5beBjxTO+sd122PxS/Gy/rcxR8oA2rrQLA1DVw93ln7hLb4dkPD0E+r1IpONwdjrRfxaXg==,iv:tAIv7KWotTFID6thP91g24PmKf2MrdZ99sz/BhBBK/4=,tag:6bbpZlw9glwWyIm2wZqUBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwc5am05st5yxwv6qm8cryngkpwq66zx6vrgjqzf5g4rnce3d5xsgr6q8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd2JNWTR1bXVHYm5YVjE3
            YVgwMmtVMVlBQUgvNGNSeFRWN3p0RnQ5VVU4CnBVUXZYMXZqSzZpbXdGWXlGeUVU
            aHdKSThTWUlMTVQxOWFvelVKcFVLWlEKLS0tIGhxL01ZK2hjOER1VWEzaVEydm95
            K1dLcVprUmdXNHc3U0YxQTdTeVRBbm8KTZU27ouFnuJef2qgKcW85ouDPbxyyT2b
            DwzUmxsLrbwrD+g8TzJMdPKN4bJcWPHyA1kO9W3tHtfwrF3CwJgmtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T17:25:50Z"
    mac: ENC[AES256_GCM,data:QD6LFWjT6JwrqwSrcOUa+XSVRtOoaik+KwD7qr9rDD5WiNh6HWcVDh0M0hjoM7Fc8B+hF/zgRDRZ3j0KHgZpJSeWbbpkd/1rB8GzILPqFV5tZK6iLL8ZWrDMAJUCH36xhlvcpwjfz+etL+ttGi3tzU866Nw0VLYwN58oH7BDaDM=,iv:+3t0neGmLoPebqOcFOQ0IjYroeLFXfzi5Z7CcK3UcCc=,tag:0TOaRX6SC0n6z8UtfMEDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
