apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:EXE/Lw5U0xHqfROMHK/e3mFIMEFtesmMByF7cuPtcX5n0WP86DfFVA==,iv:4vCdgyYrkTEd5vBT4Xb7JZ/jfEbA1CrTB6RcT+HBRrg=,tag:9J1gbq/W13h5FLKLQ6ixoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSks3TmkvUkllNFAxV1VI
            Q05TSjJjcjZrUnVnNGhPb2FPVlhZTUkwNGtJCnNpK2RoODlQSWlJdjNrQVhCRmZF
            WlBjd0w5bTFRN1Qyd25ESVhEUHJTeE0KLS0tIGF4NzdUNkpkZ2g0NTBnSHM1YWdV
            NHQ1ZTczaDNRd0JvQklCL01QWlJUNTQKpuvs49zJm6rGTuPMdM50sAPSG2EShMFp
            rj+svfjS4VIHJZveAISqFMlb6hDK0OTdf1dxAog+XIzGjNgk3iAfjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T14:14:31Z"
    mac: ENC[AES256_GCM,data:D3UyoeDyqd0dj2z+OjmWMf2qiNnhawErX9lZaoz8AKN6MVSloooN6+lRVCrx0XYYYF+vhB0IF4DlaIxsVxbPrhTEzmut2Q5dkN/HubB+Qm7F5k42YcuJ9VoCsMZOYN0CTiODFXagAEw5DlGON3+59/CD27gMvfPJ4jaCb+ANexs=,iv:ZH7S94JpYBClBIfWbgVddfq8VbVv3IHYb7rjAt7irzQ=,tag:X4Fvx/OpmyZ7WRB2ELw6vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
