apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:jr0lKkC1oQSNenubV/lNI8D3tAUjL3v2dSKpyHHLkzT/pSvdvboOIg==,iv:qcH2W5k14fVUpAjqi06Tvbi0bBlfZg3YvI8BXUbrRJM=,tag:wxuHJr8V4cP4VjErGiD8rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170zj0x7g8dlff80p95jpqdjydks68wxnu65hgtqddc3kga0cjdmqn0l4pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWm1ITEh1bU04SXJ1aExx
            UGh5Y1NoMEdyK2pucXVRVWVUVVprTEVKMEVrClR4NTJ1dUJST2ZlZzdCRGVTRHRm
            RGFDUFkxeUQrZDlWbWZtOXhrT2g1ckUKLS0tIHZJVWFGVzkrbGJSSGs1VGhrOUwy
            MFlVT2tSbDBRNDJqZENvVzhpWUdoYlEKqvE4Xx72Crmc+bkInQlKQu5hfzYUsC4z
            do6Vx6MlZ/NM2Et4L2s43MLp9PMJYNI40zf4dIpXihKnNkh+WgyieA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T19:25:08Z"
    mac: ENC[AES256_GCM,data:lGcPjoM7KMe18WytGwFcMdhKdS8bEXmXioGPqI4PTqi5rIuNVqc66FaHLpYdDRPlrUi5e5l+liTiM0tAZvl6VJNDKQeAy//Tp/k6xFsZqGAk1/5pL3zVzRYz7jPZfB5y+1NzhVBBCO239+XeXO7hZfE5YDZdSJmFZObNPQRKP10=,iv:hFnorAksK0CtoovB4eZPRAu8Y/gxf9bbABgPmgal9Bk=,tag:IQSxiBnWA9wzfFaz0Qh8NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
